-- Incremental warehouse processing graph.

USE DATABASE CLINICAL_ANALYTICS;

CREATE STREAM IF NOT EXISTS RAW.PRODUCT_EVENT_INGEST_STREAM
ON TABLE RAW.PRODUCT_EVENT
APPEND_ONLY=TRUE
COMMENT='New immutable arrivals awaiting normalized staging';

CREATE STREAM IF NOT EXISTS RAW.CLINICAL_TOOL_SNAPSHOT_STREAM
ON TABLE RAW.CLINICAL_TOOL_SNAPSHOT
APPEND_ONLY=TRUE
COMMENT='New clinical tool snapshots awaiting conformance';

CREATE STREAM IF NOT EXISTS RAW.CONTENT_SNAPSHOT_STREAM
ON TABLE RAW.CONTENT_SNAPSHOT
APPEND_ONLY=TRUE
COMMENT='New content snapshots awaiting conformance';

CREATE STREAM IF NOT EXISTS STAGING.PRODUCT_EVENT_CORE_STREAM
ON TABLE STAGING.PRODUCT_EVENT
APPEND_ONLY=TRUE
COMMENT='Normalized events awaiting canonical merge';

CREATE OR REPLACE TASK OPS.TASK_NORMALIZE_PRODUCT_EVENTS
  WAREHOUSE=TRANSFORM_WH
  SCHEDULE='1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('RAW.PRODUCT_EVENT_INGEST_STREAM')
AS
MERGE INTO STAGING.PRODUCT_EVENT T
USING (
  SELECT
    EVENT_ID,
    LOWER(EVENT_TYPE) EVENT_TYPE,
    EVENT_TS,
    SOURCE_UPDATED_AT,
    SOURCE_SYSTEM,
    COALESCE(PAYLOAD:source_version::NUMBER,1) SOURCE_VERSION,
    COALESCE(BUSINESS_KEY,EVENT_ID) BUSINESS_KEY,
    PAYLOAD:session_id::STRING SESSION_ID,
    PAYLOAD:tool_id::STRING TOOL_ID,
    PAYLOAD:content_id::STRING CONTENT_ID,
    COALESCE(PAYLOAD:account_token::STRING,PAYLOAD:account_id_token::STRING) ACCOUNT_TOKEN,
    COALESCE(PAYLOAD:user_token::STRING,PAYLOAD:user_id_token::STRING) USER_TOKEN,
    LOWER(PAYLOAD:channel::STRING) CHANNEL,
    UPPER(PAYLOAD:country_code::STRING) COUNTRY_CODE,
    LOWER(PAYLOAD:language_code::STRING) LANGUAGE_CODE,
    PAYLOAD:integration_id::STRING INTEGRATION_ID,
    PAYLOAD:query_token::STRING SEARCH_QUERY_TOKEN,
    PAYLOAD:completion_id::STRING COMPLETION_ID,
    SHA2(TO_JSON(PAYLOAD),256) CANONICAL_HASH
  FROM RAW.PRODUCT_EVENT_INGEST_STREAM
  WHERE EVENT_ID IS NOT NULL
    AND EVENT_TYPE IS NOT NULL
    AND EVENT_TS IS NOT NULL
  QUALIFY ROW_NUMBER() OVER(
    PARTITION BY EVENT_ID
    ORDER BY COALESCE(PAYLOAD:source_version::NUMBER,1) DESC,SOURCE_UPDATED_AT DESC,INGESTED_AT DESC
  )=1
) S
ON T.EVENT_ID=S.EVENT_ID
WHEN MATCHED AND (
  S.SOURCE_VERSION>T.SOURCE_VERSION OR
  (S.SOURCE_VERSION=T.SOURCE_VERSION AND S.SOURCE_UPDATED_AT>T.SOURCE_UPDATED_AT)
) THEN UPDATE SET
  EVENT_TYPE=S.EVENT_TYPE,
  EVENT_TS=S.EVENT_TS,
  SOURCE_UPDATED_AT=S.SOURCE_UPDATED_AT,
  SOURCE_SYSTEM=S.SOURCE_SYSTEM,
  SOURCE_VERSION=S.SOURCE_VERSION,
  BUSINESS_KEY=S.BUSINESS_KEY,
  SESSION_ID=S.SESSION_ID,
  TOOL_ID=S.TOOL_ID,
  CONTENT_ID=S.CONTENT_ID,
  ACCOUNT_TOKEN=S.ACCOUNT_TOKEN,
  USER_TOKEN=S.USER_TOKEN,
  CHANNEL=S.CHANNEL,
  COUNTRY_CODE=S.COUNTRY_CODE,
  LANGUAGE_CODE=S.LANGUAGE_CODE,
  INTEGRATION_ID=S.INTEGRATION_ID,
  SEARCH_QUERY_TOKEN=S.SEARCH_QUERY_TOKEN,
  COMPLETION_ID=S.COMPLETION_ID,
  CANONICAL_HASH=S.CANONICAL_HASH,
  NORMALIZED_AT=CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT(
  EVENT_ID,EVENT_TYPE,EVENT_TS,SOURCE_UPDATED_AT,SOURCE_SYSTEM,SOURCE_VERSION,
  BUSINESS_KEY,SESSION_ID,TOOL_ID,CONTENT_ID,ACCOUNT_TOKEN,USER_TOKEN,CHANNEL,
  COUNTRY_CODE,LANGUAGE_CODE,INTEGRATION_ID,SEARCH_QUERY_TOKEN,COMPLETION_ID,
  CANONICAL_HASH,NORMALIZED_AT
) VALUES(
  S.EVENT_ID,S.EVENT_TYPE,S.EVENT_TS,S.SOURCE_UPDATED_AT,S.SOURCE_SYSTEM,S.SOURCE_VERSION,
  S.BUSINESS_KEY,S.SESSION_ID,S.TOOL_ID,S.CONTENT_ID,S.ACCOUNT_TOKEN,S.USER_TOKEN,S.CHANNEL,
  S.COUNTRY_CODE,S.LANGUAGE_CODE,S.INTEGRATION_ID,S.SEARCH_QUERY_TOKEN,S.COMPLETION_ID,
  S.CANONICAL_HASH,CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TASK OPS.TASK_MERGE_PRODUCT_EVENTS
  WAREHOUSE=TRANSFORM_WH
  AFTER OPS.TASK_NORMALIZE_PRODUCT_EVENTS
  WHEN SYSTEM$STREAM_HAS_DATA('STAGING.PRODUCT_EVENT_CORE_STREAM')
AS
  CALL OPS.MERGE_PRODUCT_EVENTS();

CREATE OR REPLACE TASK OPS.TASK_REFRESH_SESSION_FACT
  WAREHOUSE=TRANSFORM_WH
  AFTER OPS.TASK_MERGE_PRODUCT_EVENTS
AS
MERGE INTO CORE.FCT_SESSION T
USING (
  SELECT
    SESSION_ID,
    TO_DATE(MIN(EVENT_TS)) SESSION_DATE,
    MAX(ACCOUNT_KEY) ACCOUNT_KEY,
    MAX(USER_TOKEN) USER_TOKEN,
    MAX(CHANNEL) CHANNEL,
    MAX(COUNTRY_CODE) COUNTRY_CODE,
    MIN(EVENT_TS) STARTED_AT,
    MAX(EVENT_TS) ENDED_AT,
    DATEDIFF('second',MIN(EVENT_TS),MAX(EVENT_TS)) DURATION_SECONDS,
    COUNT_IF(EVENT_TYPE='tool_view') TOOL_VIEWS,
    COUNT_IF(EVENT_TYPE='tool_start') TOOL_STARTS,
    COUNT_IF(EVENT_TYPE='tool_complete') TOOL_COMPLETIONS,
    COUNT_IF(EVENT_TYPE='search') SEARCHES,
    COUNT_IF(EVENT_TYPE='content_view') CONTENT_VIEWS,
    MIN_BY(EVENT_ID,EVENT_TS) FIRST_EVENT_ID,
    MAX_BY(EVENT_ID,EVENT_TS) LAST_EVENT_ID
  FROM CORE.FCT_PRODUCT_EVENT
  WHERE SESSION_ID IS NOT NULL
    AND EVENT_TS>=DATEADD('day',-2,CURRENT_TIMESTAMP())
  GROUP BY SESSION_ID
) S
ON T.SESSION_ID=S.SESSION_ID
WHEN MATCHED THEN UPDATE SET
  SESSION_DATE=S.SESSION_DATE,
  ACCOUNT_KEY=S.ACCOUNT_KEY,
  USER_TOKEN=S.USER_TOKEN,
  CHANNEL=S.CHANNEL,
  COUNTRY_CODE=S.COUNTRY_CODE,
  STARTED_AT=S.STARTED_AT,
  ENDED_AT=S.ENDED_AT,
  DURATION_SECONDS=S.DURATION_SECONDS,
  TOOL_VIEWS=S.TOOL_VIEWS,
  TOOL_STARTS=S.TOOL_STARTS,
  TOOL_COMPLETIONS=S.TOOL_COMPLETIONS,
  SEARCHES=S.SEARCHES,
  CONTENT_VIEWS=S.CONTENT_VIEWS,
  FIRST_EVENT_ID=S.FIRST_EVENT_ID,
  LAST_EVENT_ID=S.LAST_EVENT_ID,
  UPDATED_AT=CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT(
  SESSION_ID,SESSION_DATE,ACCOUNT_KEY,USER_TOKEN,CHANNEL,COUNTRY_CODE,STARTED_AT,
  ENDED_AT,DURATION_SECONDS,TOOL_VIEWS,TOOL_STARTS,TOOL_COMPLETIONS,SEARCHES,
  CONTENT_VIEWS,FIRST_EVENT_ID,LAST_EVENT_ID,UPDATED_AT
) VALUES(
  S.SESSION_ID,S.SESSION_DATE,S.ACCOUNT_KEY,S.USER_TOKEN,S.CHANNEL,S.COUNTRY_CODE,S.STARTED_AT,
  S.ENDED_AT,S.DURATION_SECONDS,S.TOOL_VIEWS,S.TOOL_STARTS,S.TOOL_COMPLETIONS,S.SEARCHES,
  S.CONTENT_VIEWS,S.FIRST_EVENT_ID,S.LAST_EVENT_ID,CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TASK OPS.TASK_PIPELINE_HEALTH_SNAPSHOT
  WAREHOUSE=BI_WH
  SCHEDULE='USING CRON */15 * * * * UTC'
AS
INSERT INTO OPS.DATA_QUALITY_RESULT(
  RUN_ID,MODEL_NAME,TEST_NAME,SEVERITY,STATUS,FAILED_ROWS,TOTAL_ROWS,FAILURE_RATIO,DETAILS
)
SELECT
  UUID_STRING(),
  'OPS.V_PIPELINE_HEALTH',
  'freshness_snapshot',
  'INFO',
  IFF(COALESCE(MAX(MINUTES_SINCE_SUCCESS),0)<=60,'PASS','FAIL'),
  COUNT_IF(MINUTES_SINCE_SUCCESS>60),
  COUNT(*),
  DIV0(COUNT_IF(MINUTES_SINCE_SUCCESS>60),COUNT(*)),
  OBJECT_CONSTRUCT('captured_at',CURRENT_TIMESTAMP())
FROM OPS.V_PIPELINE_HEALTH;

-- Deployment automation resumes the root tasks after validating dependencies and grants.
-- ALTER TASK OPS.TASK_NORMALIZE_PRODUCT_EVENTS RESUME;
-- ALTER TASK OPS.TASK_PIPELINE_HEALTH_SNAPSHOT RESUME;
