-- Continuous and incremental processing graph for the clinical decision-support reference platform.
-- This file deliberately separates ingestion CDC, deterministic merge, continuous serving views,
-- and operational monitoring. Deployment automation should validate grants and objects before RESUME.

USE DATABASE CLINICAL_ANALYTICS;

-- -----------------------------------------------------------------------------
-- CHANGE DATA CAPTURE
-- -----------------------------------------------------------------------------
CREATE STREAM IF NOT EXISTS RAW.PRODUCT_EVENT_INGEST_STREAM
ON TABLE RAW.PRODUCT_EVENT
APPEND_ONLY=TRUE
COMMENT='New immutable product/search/CME/EHR telemetry arrivals awaiting normalization';

CREATE STREAM IF NOT EXISTS RAW.CLINICAL_TOOL_SNAPSHOT_STREAM
ON TABLE RAW.CLINICAL_TOOL_SNAPSHOT
APPEND_ONLY=TRUE
COMMENT='Versioned clinical tool metadata awaiting conformance';

CREATE STREAM IF NOT EXISTS RAW.CONTENT_SNAPSHOT_STREAM
ON TABLE RAW.CONTENT_SNAPSHOT
APPEND_ONLY=TRUE
COMMENT='Guideline/editorial/CME content metadata awaiting conformance';

CREATE STREAM IF NOT EXISTS RAW.QUALITY_RATING_SNAPSHOT_STREAM
ON TABLE RAW.QUALITY_RATING_SNAPSHOT
APPEND_ONLY=TRUE
COMMENT='Reference quality-rating updates awaiting conformance';

CREATE STREAM IF NOT EXISTS STAGING.PRODUCT_EVENT_CORE_STREAM
ON TABLE STAGING.PRODUCT_EVENT
APPEND_ONLY=TRUE
COMMENT='Normalized events awaiting canonical fact merge';

-- -----------------------------------------------------------------------------
-- PRODUCT EVENT NORMALIZATION
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TASK OPS.TASK_NORMALIZE_PRODUCT_EVENTS
  WAREHOUSE=TRANSFORM_WH
  SCHEDULE='1 MINUTE'
  ALLOW_OVERLAPPING_EXECUTION=FALSE
  WHEN SYSTEM$STREAM_HAS_DATA('RAW.PRODUCT_EVENT_INGEST_STREAM')
AS
MERGE INTO STAGING.PRODUCT_EVENT T
USING (
  SELECT
    EVENT_ID,
    LOWER(EVENT_TYPE) EVENT_TYPE,
    EVENT_TS,
    SOURCE_UPDATED_AT,
    SOURCE_SYSTEM,
    COALESCE(PAYLOAD:source_version::NUMBER,1) SOURCE_VERSION,
    COALESCE(BUSINESS_KEY,EVENT_ID) BUSINESS_KEY,
    PAYLOAD:session_id::STRING SESSION_ID,
    PAYLOAD:tool_id::STRING TOOL_ID,
    PAYLOAD:content_id::STRING CONTENT_ID,
    PAYLOAD:quality_rating_id::STRING QUALITY_RATING_ID,
    COALESCE(PAYLOAD:account_token::STRING,PAYLOAD:account_id_token::STRING) ACCOUNT_TOKEN,
    COALESCE(PAYLOAD:user_token::STRING,PAYLOAD:user_id_token::STRING) USER_TOKEN,
    PAYLOAD:organization_token::STRING ORGANIZATION_TOKEN,
    LOWER(COALESCE(PAYLOAD:channel::STRING,'web')) CHANNEL,
    UPPER(COALESCE(PAYLOAD:country_code::STRING,'ZZ')) COUNTRY_CODE,
    LOWER(PAYLOAD:language_code::STRING) LANGUAGE_CODE,
    PAYLOAD:integration_id::STRING INTEGRATION_ID,
    PAYLOAD:query_token::STRING SEARCH_QUERY_TOKEN,
    TRY_TO_NUMBER(PAYLOAD:search_result_rank::STRING) SEARCH_RESULT_RANK,
    PAYLOAD:completion_id::STRING COMPLETION_ID,
    PAYLOAD:result_band::STRING RESULT_BAND,
    TRY_TO_NUMBER(PAYLOAD:input_count::STRING) INPUT_COUNT,
    TRY_TO_NUMBER(PAYLOAD:autofill_field_count::STRING) AUTOFILL_FIELD_COUNT,
    TRY_TO_NUMBER(PAYLOAD:autofill_confirmed_count::STRING) AUTOFILL_CONFIRMED_COUNT,
    PAYLOAD:confidence_band::STRING CONFIDENCE_BAND,
    PAYLOAD:recommendation_model::STRING RECOMMENDATION_MODEL,
    TRY_TO_NUMBER(PAYLOAD:recommendation_position::STRING) RECOMMENDATION_POSITION,
    TRY_TO_DOUBLE(PAYLOAD:cme_credit_hours::STRING) CME_CREDIT_HOURS,
    PAYLOAD:experiment_assignments EXPERIMENT_ASSIGNMENTS,
    SHA2(TO_JSON(PAYLOAD),256) CANONICAL_HASH
  FROM RAW.PRODUCT_EVENT_INGEST_STREAM
  WHERE EVENT_ID IS NOT NULL
    AND EVENT_TYPE IS NOT NULL
    AND EVENT_TS IS NOT NULL
    AND SOURCE_UPDATED_AT IS NOT NULL
  QUALIFY ROW_NUMBER() OVER(
    PARTITION BY EVENT_ID
    ORDER BY COALESCE(PAYLOAD:source_version::NUMBER,1) DESC,
             SOURCE_UPDATED_AT DESC,
             INGESTED_AT DESC
  )=1
) S
ON T.EVENT_ID=S.EVENT_ID
WHEN MATCHED AND (
  S.SOURCE_VERSION>T.SOURCE_VERSION OR
  (S.SOURCE_VERSION=T.SOURCE_VERSION AND S.SOURCE_UPDATED_AT>T.SOURCE_UPDATED_AT)
) THEN UPDATE SET
  EVENT_TYPE=S.EVENT_TYPE,
  EVENT_TS=S.EVENT_TS,
  SOURCE_UPDATED_AT=S.SOURCE_UPDATED_AT,
  SOURCE_SYSTEM=S.SOURCE_SYSTEM,
  SOURCE_VERSION=S.SOURCE_VERSION,
  BUSINESS_KEY=S.BUSINESS_KEY,
  SESSION_ID=S.SESSION_ID,
  TOOL_ID=S.TOOL_ID,
  CONTENT_ID=S.CONTENT_ID,
  QUALITY_RATING_ID=S.QUALITY_RATING_ID,
  ACCOUNT_TOKEN=S.ACCOUNT_TOKEN,
  USER_TOKEN=S.USER_TOKEN,
  ORGANIZATION_TOKEN=S.ORGANIZATION_TOKEN,
  CHANNEL=S.CHANNEL,
  COUNTRY_CODE=S.COUNTRY_CODE,
  LANGUAGE_CODE=S.LANGUAGE_CODE,
  INTEGRATION_ID=S.INTEGRATION_ID,
  SEARCH_QUERY_TOKEN=S.SEARCH_QUERY_TOKEN,
  SEARCH_RESULT_RANK=S.SEARCH_RESULT_RANK,
  COMPLETION_ID=S.COMPLETION_ID,
  RESULT_BAND=S.RESULT_BAND,
  INPUT_COUNT=S.INPUT_COUNT,
  AUTOFILL_FIELD_COUNT=S.AUTOFILL_FIELD_COUNT,
  AUTOFILL_CONFIRMED_COUNT=S.AUTOFILL_CONFIRMED_COUNT,
  CONFIDENCE_BAND=S.CONFIDENCE_BAND,
  RECOMMENDATION_MODEL=S.RECOMMENDATION_MODEL,
  RECOMMENDATION_POSITION=S.RECOMMENDATION_POSITION,
  CME_CREDIT_HOURS=S.CME_CREDIT_HOURS,
  EXPERIMENT_ASSIGNMENTS=S.EXPERIMENT_ASSIGNMENTS,
  CANONICAL_HASH=S.CANONICAL_HASH,
  NORMALIZED_AT=CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT(
  EVENT_ID,EVENT_TYPE,EVENT_TS,SOURCE_UPDATED_AT,SOURCE_SYSTEM,SOURCE_VERSION,
  BUSINESS_KEY,SESSION_ID,TOOL_ID,CONTENT_ID,QUALITY_RATING_ID,ACCOUNT_TOKEN,USER_TOKEN,
  ORGANIZATION_TOKEN,CHANNEL,COUNTRY_CODE,LANGUAGE_CODE,INTEGRATION_ID,SEARCH_QUERY_TOKEN,
  SEARCH_RESULT_RANK,COMPLETION_ID,RESULT_BAND,INPUT_COUNT,AUTOFILL_FIELD_COUNT,
  AUTOFILL_CONFIRMED_COUNT,CONFIDENCE_BAND,RECOMMENDATION_MODEL,RECOMMENDATION_POSITION,
  CME_CREDIT_HOURS,EXPERIMENT_ASSIGNMENTS,CANONICAL_HASH,NORMALIZED_AT
) VALUES(
  S.EVENT_ID,S.EVENT_TYPE,S.EVENT_TS,S.SOURCE_UPDATED_AT,S.SOURCE_SYSTEM,S.SOURCE_VERSION,
  S.BUSINESS_KEY,S.SESSION_ID,S.TOOL_ID,S.CONTENT_ID,S.QUALITY_RATING_ID,S.ACCOUNT_TOKEN,S.USER_TOKEN,
  S.ORGANIZATION_TOKEN,S.CHANNEL,S.COUNTRY_CODE,S.LANGUAGE_CODE,S.INTEGRATION_ID,S.SEARCH_QUERY_TOKEN,
  S.SEARCH_RESULT_RANK,S.COMPLETION_ID,S.RESULT_BAND,S.INPUT_COUNT,S.AUTOFILL_FIELD_COUNT,
  S.AUTOFILL_CONFIRMED_COUNT,S.CONFIDENCE_BAND,S.RECOMMENDATION_MODEL,S.RECOMMENDATION_POSITION,
  S.CME_CREDIT_HOURS,S.EXPERIMENT_ASSIGNMENTS,S.CANONICAL_HASH,CURRENT_TIMESTAMP()
);

-- -----------------------------------------------------------------------------
-- ROOT TASK GRAPH
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TASK OPS.TASK_MERGE_PRODUCT_EVENTS
  WAREHOUSE=TRANSFORM_WH
  AFTER OPS.TASK_NORMALIZE_PRODUCT_EVENTS
  WHEN SYSTEM$STREAM_HAS_DATA('STAGING.PRODUCT_EVENT_CORE_STREAM')
AS
  CALL OPS.MERGE_PRODUCT_EVENTS();

CREATE OR REPLACE TASK OPS.TASK_REFRESH_SESSION_FACT
  WAREHOUSE=TRANSFORM_WH
  AFTER OPS.TASK_MERGE_PRODUCT_EVENTS
AS
MERGE INTO CORE.FCT_SESSION T
USING (
  SELECT
    SESSION_ID,
    TO_DATE(MIN(EVENT_TS)) SESSION_DATE,
    MAX(ACCOUNT_KEY) ACCOUNT_KEY,
    MAX(USER_TOKEN) USER_TOKEN,
    MAX(CHANNEL) CHANNEL,
    MAX(COUNTRY_CODE) COUNTRY_CODE,
    MIN(EVENT_TS) STARTED_AT,
    MAX(EVENT_TS) ENDED_AT,
    DATEDIFF('second',MIN(EVENT_TS),MAX(EVENT_TS)) DURATION_SECONDS,
    COUNT_IF(EVENT_TYPE='tool_view') TOOL_VIEWS,
    COUNT_IF(EVENT_TYPE='tool_start') TOOL_STARTS,
    COUNT_IF(EVENT_TYPE='tool_complete') TOOL_COMPLETIONS,
    COUNT_IF(EVENT_TYPE='search') SEARCHES,
    COUNT_IF(EVENT_TYPE IN ('content_view','guideline_view','cme_content_view')) CONTENT_VIEWS,
    MIN_BY(EVENT_ID,EVENT_TS) FIRST_EVENT_ID,
    MAX_BY(EVENT_ID,EVENT_TS) LAST_EVENT_ID
  FROM CORE.FCT_PRODUCT_EVENT
  WHERE SESSION_ID IS NOT NULL
    AND EVENT_TS>=DATEADD('day',-2,CURRENT_TIMESTAMP())
  GROUP BY SESSION_ID
) S
ON T.SESSION_ID=S.SESSION_ID
WHEN MATCHED THEN UPDATE SET
  SESSION_DATE=S.SESSION_DATE,
  ACCOUNT_KEY=S.ACCOUNT_KEY,
  USER_TOKEN=S.USER_TOKEN,
  CHANNEL=S.CHANNEL,
  COUNTRY_CODE=S.COUNTRY_CODE,
  STARTED_AT=S.STARTED_AT,
  ENDED_AT=S.ENDED_AT,
  DURATION_SECONDS=S.DURATION_SECONDS,
  TOOL_VIEWS=S.TOOL_VIEWS,
  TOOL_STARTS=S.TOOL_STARTS,
  TOOL_COMPLETIONS=S.TOOL_COMPLETIONS,
  SEARCHES=S.SEARCHES,
  CONTENT_VIEWS=S.CONTENT_VIEWS,
  FIRST_EVENT_ID=S.FIRST_EVENT_ID,
  LAST_EVENT_ID=S.LAST_EVENT_ID,
  UPDATED_AT=CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT(
  SESSION_ID,SESSION_DATE,ACCOUNT_KEY,USER_TOKEN,CHANNEL,COUNTRY_CODE,STARTED_AT,
  ENDED_AT,DURATION_SECONDS,TOOL_VIEWS,TOOL_STARTS,TOOL_COMPLETIONS,SEARCHES,
  CONTENT_VIEWS,FIRST_EVENT_ID,LAST_EVENT_ID,UPDATED_AT
) VALUES(
  S.SESSION_ID,S.SESSION_DATE,S.ACCOUNT_KEY,S.USER_TOKEN,S.CHANNEL,S.COUNTRY_CODE,S.STARTED_AT,
  S.ENDED_AT,S.DURATION_SECONDS,S.TOOL_VIEWS,S.TOOL_STARTS,S.TOOL_COMPLETIONS,S.SEARCHES,
  S.CONTENT_VIEWS,S.FIRST_EVENT_ID,S.LAST_EVENT_ID,CURRENT_TIMESTAMP()
);

-- -----------------------------------------------------------------------------
-- CONTINUOUS QUERY / DYNAMIC TABLE SERVING LAYER
-- -----------------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE MART.DT_LIVE_TOOL_FUNNEL
  TARGET_LAG='1 minute'
  WAREHOUSE=BI_WH
  REFRESH_MODE=INCREMENTAL
  INITIALIZE=ON_CREATE
AS
SELECT
  E.EVENT_DATE,
  E.TOOL_ID,
  T.TOOL_NAME,
  T.PRIMARY_SPECIALTY,
  E.CHANNEL,
  E.COUNTRY_CODE,
  COUNT_IF(E.EVENT_TYPE='tool_view') AS TOOL_VIEWS,
  COUNT_IF(E.EVENT_TYPE='tool_start') AS TOOL_STARTS,
  COUNT_IF(E.EVENT_TYPE='tool_complete') AS TOOL_COMPLETIONS,
  COUNT_IF(E.EVENT_TYPE='favorite_add') AS FAVORITE_ADDS,
  COUNT(DISTINCT E.USER_TOKEN) AS UNIQUE_USERS,
  COUNT(DISTINCT E.SESSION_ID) AS SESSIONS,
  DIV0(COUNT_IF(E.EVENT_TYPE='tool_start'),COUNT_IF(E.EVENT_TYPE='tool_view')) AS VIEW_TO_START_RATE,
  DIV0(COUNT_IF(E.EVENT_TYPE='tool_complete'),COUNT_IF(E.EVENT_TYPE='tool_start')) AS START_TO_COMPLETE_RATE
FROM CORE.FCT_PRODUCT_EVENT E
LEFT JOIN CORE.DIM_CLINICAL_TOOL T
  ON E.CLINICAL_TOOL_KEY=T.CLINICAL_TOOL_KEY
WHERE E.EVENT_TS >= DATEADD('day',-2,CURRENT_TIMESTAMP())
GROUP BY 1,2,3,4,5,6;

CREATE OR REPLACE DYNAMIC TABLE MART.DT_LIVE_SEARCH_DISCOVERY
  TARGET_LAG='1 minute'
  WAREHOUSE=BI_WH
  REFRESH_MODE=INCREMENTAL
  INITIALIZE=ON_CREATE
AS
SELECT
  EVENT_DATE,
  CHANNEL,
  COUNTRY_CODE,
  COUNT_IF(EVENT_TYPE='search') SEARCHES,
  COUNT_IF(EVENT_TYPE='search_result_click') SEARCH_RESULT_CLICKS,
  COUNT_IF(EVENT_TYPE='tool_view') TOOL_VIEWS,
  COUNT_IF(EVENT_TYPE='tool_complete') TOOL_COMPLETIONS,
  COUNT(DISTINCT SEARCH_QUERY_TOKEN) UNIQUE_QUERY_TOKENS,
  COUNT(DISTINCT USER_TOKEN) UNIQUE_USERS
FROM CORE.FCT_PRODUCT_EVENT
WHERE EVENT_TS >= DATEADD('day',-2,CURRENT_TIMESTAMP())
GROUP BY 1,2,3;

CREATE OR REPLACE DYNAMIC TABLE MART.DT_LIVE_EHR_INTEGRATION
  TARGET_LAG='1 minute'
  WAREHOUSE=BI_WH
  REFRESH_MODE=INCREMENTAL
  INITIALIZE=ON_CREATE
AS
SELECT
  EVENT_DATE,
  COALESCE(INTEGRATION_ID,'unknown') INTEGRATION_ID,
  COUNT_IF(EVENT_TYPE='integration_launch') LAUNCHES,
  COUNT_IF(EVENT_TYPE='ehr_context_open') CONTEXT_OPENS,
  COUNT_IF(EVENT_TYPE='ehr_autofill') AUTOFILL_EVENTS,
  COUNT_IF(EVENT_TYPE='ehr_result_writeback') WRITEBACKS,
  SUM(COALESCE(AUTOFILL_FIELD_COUNT,0)) AUTOFILL_FIELDS,
  SUM(COALESCE(AUTOFILL_CONFIRMED_COUNT,0)) CONFIRMED_FIELDS,
  DIV0(SUM(COALESCE(AUTOFILL_CONFIRMED_COUNT,0)),SUM(COALESCE(AUTOFILL_FIELD_COUNT,0))) CONFIRMATION_RATE,
  COUNT(DISTINCT TOOL_ID) UNIQUE_TOOLS,
  COUNT(DISTINCT ACCOUNT_KEY) UNIQUE_ACCOUNTS
FROM CORE.FCT_PRODUCT_EVENT
WHERE EVENT_TS >= DATEADD('day',-2,CURRENT_TIMESTAMP())
  AND (INTEGRATION_ID IS NOT NULL OR EVENT_TYPE LIKE 'ehr_%' OR EVENT_TYPE='integration_launch')
GROUP BY 1,2;

CREATE OR REPLACE DYNAMIC TABLE OPS.DT_CONTINUOUS_PIPELINE_SLO
  TARGET_LAG='2 minutes'
  WAREHOUSE=BI_WH
  REFRESH_MODE=INCREMENTAL
  INITIALIZE=ON_CREATE
AS
SELECT
  PIPELINE_NAME,
  MAX_BY(RUN_ID,STARTED_AT) LAST_RUN_ID,
  MAX(STARTED_AT) LAST_STARTED_AT,
  MAX(COMPLETED_AT) LAST_COMPLETED_AT,
  MAX_BY(STATUS,STARTED_AT) LAST_STATUS,
  MAX_BY(SOURCE_COUNT,STARTED_AT) LAST_SOURCE_COUNT,
  MAX_BY(QUARANTINED_COUNT,STARTED_AT) LAST_QUARANTINED_COUNT,
  DATEDIFF('second',MAX(COMPLETED_AT),CURRENT_TIMESTAMP()) FRESHNESS_SECONDS,
  DIV0(MAX_BY(QUARANTINED_COUNT,STARTED_AT),NULLIF(MAX_BY(SOURCE_COUNT,STARTED_AT),0)) QUARANTINE_RATIO,
  COUNT_IF(STARTED_AT >= DATEADD('hour',-24,CURRENT_TIMESTAMP()) AND STATUS<>'SUCCESS') FAILURES_24H
FROM OPS.PIPELINE_RUN
GROUP BY PIPELINE_NAME;

-- Dynamic-table refresh diagnostics: useful for continuous-query SLO evidence.
CREATE OR REPLACE VIEW OPS.V_DYNAMIC_TABLE_REFRESH_HEALTH AS
SELECT
  NAME,
  SCHEMA_NAME,
  DATABASE_NAME,
  STATE,
  REFRESH_START_TIME,
  REFRESH_END_TIME,
  COMPLETION_TARGET,
  DATA_TIMESTAMP,
  DATEDIFF('second',DATA_TIMESTAMP,CURRENT_TIMESTAMP()) DATA_AGE_SECONDS,
  REFRESH_ACTION,
  REFRESH_TRIGGER,
  ERROR_CODE,
  ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
  DATE_RANGE_START=>DATEADD('hour',-24,CURRENT_TIMESTAMP()),
  DATE_RANGE_END=>CURRENT_TIMESTAMP()
));

-- -----------------------------------------------------------------------------
-- PERIODIC QUALITY SNAPSHOT
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TASK OPS.TASK_PIPELINE_HEALTH_SNAPSHOT
  WAREHOUSE=BI_WH
  SCHEDULE='USING CRON */15 * * * * UTC'
  ALLOW_OVERLAPPING_EXECUTION=FALSE
AS
INSERT INTO OPS.DATA_QUALITY_RESULT(
  RUN_ID,MODEL_NAME,TEST_NAME,SEVERITY,STATUS,FAILED_ROWS,TOTAL_ROWS,FAILURE_RATIO,DETAILS
)
SELECT
  UUID_STRING(),
  'OPS.DT_CONTINUOUS_PIPELINE_SLO',
  'continuous_freshness_snapshot',
  'ERROR',
  IFF(COUNT_IF(FRESHNESS_SECONDS>3600 OR LAST_STATUS<>'SUCCESS')=0,'PASS','FAIL'),
  COUNT_IF(FRESHNESS_SECONDS>3600 OR LAST_STATUS<>'SUCCESS'),
  COUNT(*),
  DIV0(COUNT_IF(FRESHNESS_SECONDS>3600 OR LAST_STATUS<>'SUCCESS'),COUNT(*)),
  OBJECT_CONSTRUCT('captured_at',CURRENT_TIMESTAMP(),'max_freshness_seconds',3600)
FROM OPS.DT_CONTINUOUS_PIPELINE_SLO;

-- Deployment automation resumes root scheduled tasks only after validating dependencies/grants.
-- Child tasks are resumed before their root task in Snowflake task graphs.
-- ALTER TASK OPS.TASK_REFRESH_SESSION_FACT RESUME;
-- ALTER TASK OPS.TASK_MERGE_PRODUCT_EVENTS RESUME;
-- ALTER TASK OPS.TASK_NORMALIZE_PRODUCT_EVENTS RESUME;
-- ALTER TASK OPS.TASK_PIPELINE_HEALTH_SNAPSHOT RESUME;
