CREATE DATABASE IF NOT EXISTS CLINICAL_ANALYTICS;
USE DATABASE CLINICAL_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW COMMENT='Immutable landing objects';
CREATE SCHEMA IF NOT EXISTS STAGING COMMENT='Validated normalized records';
CREATE SCHEMA IF NOT EXISTS CORE COMMENT='Conformed dimensions and canonical facts';
CREATE SCHEMA IF NOT EXISTS MART COMMENT='Business-facing analytical products';
CREATE SCHEMA IF NOT EXISTS OPS COMMENT='Pipeline controls and observability';
CREATE SCHEMA IF NOT EXISTS GOVERNANCE COMMENT='Ownership and policy metadata';

CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
  WAREHOUSE_SIZE='XSMALL'
  AUTO_SUSPEND=60
  AUTO_RESUME=TRUE
  INITIALLY_SUSPENDED=TRUE
  STATEMENT_TIMEOUT_IN_SECONDS=1800
  COMMENT='Bounded ingestion and COPY workloads';

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE='SMALL'
  AUTO_SUSPEND=60
  AUTO_RESUME=TRUE
  INITIALLY_SUSPENDED=TRUE
  STATEMENT_TIMEOUT_IN_SECONDS=3600
  COMMENT='dbt transformation and merge workloads';

CREATE WAREHOUSE IF NOT EXISTS BI_WH
  WAREHOUSE_SIZE='XSMALL'
  AUTO_SUSPEND=120
  AUTO_RESUME=TRUE
  INITIALLY_SUSPENDED=TRUE
  STATEMENT_TIMEOUT_IN_SECONDS=600
  COMMENT='Interactive analytics workloads';

ALTER DATABASE CLINICAL_ANALYTICS SET DATA_RETENTION_TIME_IN_DAYS=7;
ALTER SCHEMA RAW SET DATA_RETENTION_TIME_IN_DAYS=14;
ALTER SCHEMA STAGING SET DATA_RETENTION_TIME_IN_DAYS=7;
ALTER SCHEMA CORE SET DATA_RETENTION_TIME_IN_DAYS=7;
ALTER SCHEMA MART SET DATA_RETENTION_TIME_IN_DAYS=3;
ALTER SCHEMA OPS SET DATA_RETENTION_TIME_IN_DAYS=14;
