-- Transactional warehouse procedures for deterministic publication, reconciliation, replay,
-- and watermark control. Procedures return structured VARIANT payloads for orchestration logs.

USE DATABASE CLINICAL_ANALYTICS;

CREATE OR REPLACE PROCEDURE OPS.BEGIN_PIPELINE_RUN(
    RUN_ID STRING,
    PIPELINE_NAME STRING,
    WATERMARK_LOW TIMESTAMP_TZ,
    WATERMARK_HIGH TIMESTAMP_TZ,
    QUERY_TAG STRING,
    GIT_SHA STRING
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    IF (:WATERMARK_LOW IS NOT NULL AND :WATERMARK_HIGH IS NOT NULL AND :WATERMARK_HIGH <= :WATERMARK_LOW) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','invalid_watermark_window');
    END IF;

    MERGE INTO OPS.PIPELINE_RUN T
    USING (
      SELECT :RUN_ID RUN_ID,:PIPELINE_NAME PIPELINE_NAME,:WATERMARK_LOW WATERMARK_LOW,
             :WATERMARK_HIGH WATERMARK_HIGH,:QUERY_TAG QUERY_TAG,:GIT_SHA GIT_SHA
    ) S
    ON T.RUN_ID=S.RUN_ID
    WHEN MATCHED THEN UPDATE SET
      T.PIPELINE_NAME=S.PIPELINE_NAME,T.STARTED_AT=CURRENT_TIMESTAMP(),T.COMPLETED_AT=NULL,
      T.STATUS='RUNNING',T.SOURCE_WATERMARK_LOW=S.WATERMARK_LOW,T.SOURCE_WATERMARK_HIGH=S.WATERMARK_HIGH,
      T.QUERY_TAG=S.QUERY_TAG,T.GIT_SHA=S.GIT_SHA,T.ERROR_CLASS=NULL,T.ERROR_MESSAGE=NULL
    WHEN NOT MATCHED THEN INSERT (
      RUN_ID,PIPELINE_NAME,STARTED_AT,STATUS,SOURCE_WATERMARK_LOW,SOURCE_WATERMARK_HIGH,QUERY_TAG,GIT_SHA
    ) VALUES (
      S.RUN_ID,S.PIPELINE_NAME,CURRENT_TIMESTAMP(),'RUNNING',S.WATERMARK_LOW,S.WATERMARK_HIGH,S.QUERY_TAG,S.GIT_SHA
    );

    RETURN OBJECT_CONSTRUCT('run_id',:RUN_ID,'status','RUNNING','started_at',CURRENT_TIMESTAMP());
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.RECORD_QUALITY_RESULT(
    RUN_ID STRING,
    MODEL_NAME STRING,
    TEST_NAME STRING,
    SEVERITY STRING,
    STATUS STRING,
    FAILED_ROWS NUMBER,
    TOTAL_ROWS NUMBER,
    DETAILS VARIANT
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE FAILURE_RATIO FLOAT;
BEGIN
    FAILURE_RATIO := IFF(:TOTAL_ROWS=0,0,:FAILED_ROWS/:TOTAL_ROWS);
    MERGE INTO OPS.DATA_QUALITY_RESULT T
    USING (SELECT :RUN_ID RUN_ID,:MODEL_NAME MODEL_NAME,:TEST_NAME TEST_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.MODEL_NAME=S.MODEL_NAME AND T.TEST_NAME=S.TEST_NAME
    WHEN MATCHED THEN UPDATE SET
      SEVERITY=:SEVERITY,STATUS=:STATUS,FAILED_ROWS=:FAILED_ROWS,TOTAL_ROWS=:TOTAL_ROWS,
      FAILURE_RATIO=:FAILURE_RATIO,OBSERVED_AT=CURRENT_TIMESTAMP(),DETAILS=:DETAILS
    WHEN NOT MATCHED THEN INSERT (
      RUN_ID,MODEL_NAME,TEST_NAME,SEVERITY,STATUS,FAILED_ROWS,TOTAL_ROWS,FAILURE_RATIO,OBSERVED_AT,DETAILS
    ) VALUES (
      :RUN_ID,:MODEL_NAME,:TEST_NAME,:SEVERITY,:STATUS,:FAILED_ROWS,:TOTAL_ROWS,
      :FAILURE_RATIO,CURRENT_TIMESTAMP(),:DETAILS
    );
    RETURN OBJECT_CONSTRUCT('run_id',:RUN_ID,'model_name',:MODEL_NAME,'test_name',:TEST_NAME,
      'status',:STATUS,'failure_ratio',:FAILURE_RATIO);
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.RECONCILE_PRODUCT_EVENT_WINDOW(
    RUN_ID STRING,
    WINDOW_LOW TIMESTAMP_TZ,
    WINDOW_HIGH TIMESTAMP_TZ
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    RAW_COUNT NUMBER;
    STAGED_COUNT NUMBER;
    CORE_COUNT NUMBER;
    RAW_DISTINCT NUMBER;
    STAGED_DISTINCT NUMBER;
    CORE_DISTINCT NUMBER;
    RAW_COMPLETIONS NUMBER;
    CORE_COMPLETIONS NUMBER;
    STAGE_HASH NUMBER;
    CORE_HASH NUMBER;
    FAILURES NUMBER DEFAULT 0;
BEGIN
    SELECT COUNT(*),COUNT(DISTINCT EVENT_ID),COUNT_IF(LOWER(EVENT_TYPE)='tool_complete')
      INTO :RAW_COUNT,:RAW_DISTINCT,:RAW_COMPLETIONS
    FROM RAW.PRODUCT_EVENT
    WHERE EVENT_TS >= :WINDOW_LOW AND EVENT_TS < :WINDOW_HIGH;

    SELECT COUNT(*),COUNT(DISTINCT EVENT_ID),
           HASH_AGG(EVENT_ID,EVENT_TYPE,BUSINESS_KEY,SOURCE_VERSION)
      INTO :STAGED_COUNT,:STAGED_DISTINCT,:STAGE_HASH
    FROM STAGING.PRODUCT_EVENT
    WHERE EVENT_TS >= :WINDOW_LOW AND EVENT_TS < :WINDOW_HIGH;

    SELECT COUNT(*),COUNT(DISTINCT EVENT_ID),COUNT_IF(EVENT_TYPE='tool_complete'),
           HASH_AGG(EVENT_ID,EVENT_TYPE,BUSINESS_KEY,SOURCE_VERSION)
      INTO :CORE_COUNT,:CORE_DISTINCT,:CORE_COMPLETIONS,:CORE_HASH
    FROM CORE.FCT_PRODUCT_EVENT
    WHERE EVENT_TS >= :WINDOW_LOW AND EVENT_TS < :WINDOW_HIGH;

    DELETE FROM OPS.RECONCILIATION_RESULT WHERE RUN_ID=:RUN_ID;

    INSERT INTO OPS.RECONCILIATION_RESULT(
      RUN_ID,CONTROL_NAME,SOURCE_VALUE,TARGET_VALUE,DIFFERENCE_VALUE,TOLERANCE_VALUE,STATUS,DETAILS
    ) VALUES
      (:RUN_ID,'raw_to_staging_distinct_events',:RAW_DISTINCT,:STAGED_DISTINCT,:RAW_DISTINCT-:STAGED_DISTINCT,0,
       IFF(:RAW_DISTINCT=:STAGED_DISTINCT,'PASS','FAIL'),OBJECT_CONSTRUCT('window_low',:WINDOW_LOW,'window_high',:WINDOW_HIGH,'raw_rows',:RAW_COUNT,'staged_rows',:STAGED_COUNT)),
      (:RUN_ID,'staging_to_core_distinct_events',:STAGED_DISTINCT,:CORE_DISTINCT,:STAGED_DISTINCT-:CORE_DISTINCT,0,
       IFF(:STAGED_DISTINCT=:CORE_DISTINCT,'PASS','FAIL'),OBJECT_CONSTRUCT('staged_rows',:STAGED_COUNT,'core_rows',:CORE_COUNT)),
      (:RUN_ID,'tool_completion_count',:RAW_COMPLETIONS,:CORE_COMPLETIONS,:RAW_COMPLETIONS-:CORE_COMPLETIONS,0,
       IFF(:RAW_COMPLETIONS=:CORE_COMPLETIONS,'PASS','FAIL'),OBJECT_CONSTRUCT('event_type','tool_complete')),
      (:RUN_ID,'staging_core_identity_hash',:STAGE_HASH,:CORE_HASH,:STAGE_HASH-:CORE_HASH,0,
       IFF(:STAGE_HASH=:CORE_HASH,'PASS','FAIL'),OBJECT_CONSTRUCT('fields',ARRAY_CONSTRUCT('event_id','event_type','business_key','source_version')));

    -- Event-type distribution catches offsetting count errors that a total row count can hide.
    INSERT INTO OPS.RECONCILIATION_RESULT(
      RUN_ID,CONTROL_NAME,SOURCE_VALUE,TARGET_VALUE,DIFFERENCE_VALUE,TOLERANCE_VALUE,STATUS,DETAILS
    )
    WITH S AS (
      SELECT EVENT_TYPE,COUNT(*) C FROM STAGING.PRODUCT_EVENT
      WHERE EVENT_TS>=:WINDOW_LOW AND EVENT_TS<:WINDOW_HIGH GROUP BY 1
    ), T AS (
      SELECT EVENT_TYPE,COUNT(*) C FROM CORE.FCT_PRODUCT_EVENT
      WHERE EVENT_TS>=:WINDOW_LOW AND EVENT_TS<:WINDOW_HIGH GROUP BY 1
    )
    SELECT :RUN_ID,'event_type_distribution:'||COALESCE(S.EVENT_TYPE,T.EVENT_TYPE),
      COALESCE(S.C,0),COALESCE(T.C,0),COALESCE(S.C,0)-COALESCE(T.C,0),0,
      IFF(COALESCE(S.C,0)=COALESCE(T.C,0),'PASS','FAIL'),
      OBJECT_CONSTRUCT('event_type',COALESCE(S.EVENT_TYPE,T.EVENT_TYPE))
    FROM S FULL OUTER JOIN T USING(EVENT_TYPE);

    SELECT COUNT(*) INTO :FAILURES FROM OPS.RECONCILIATION_RESULT
    WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';

    RETURN OBJECT_CONSTRUCT('run_id',:RUN_ID,'raw_count',:RAW_COUNT,'staging_count',:STAGED_COUNT,
      'core_count',:CORE_COUNT,'failed_controls',:FAILURES,'status',IFF(:FAILURES=0,'PASS','FAIL'));
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.RECONCILE_CLINICAL_TOOL_CATALOG(RUN_ID STRING)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE RAW_CURRENT NUMBER; CORE_CURRENT NUMBER; DUP_CURRENT NUMBER; MISSING_NAMES NUMBER; FAILURES NUMBER;
BEGIN
    SELECT COUNT(DISTINCT SOURCE_TOOL_ID) INTO :RAW_CURRENT FROM RAW.CLINICAL_TOOL_SNAPSHOT;
    SELECT COUNT_IF(IS_CURRENT),COUNT_IF(IS_CURRENT AND TOOL_NAME IS NULL)
      INTO :CORE_CURRENT,:MISSING_NAMES FROM CORE.DIM_CLINICAL_TOOL;
    SELECT COUNT(*) INTO :DUP_CURRENT FROM (
      SELECT TOOL_ID FROM CORE.DIM_CLINICAL_TOOL WHERE IS_CURRENT GROUP BY TOOL_ID HAVING COUNT(*)>1
    );

    INSERT INTO OPS.RECONCILIATION_RESULT(RUN_ID,CONTROL_NAME,SOURCE_VALUE,TARGET_VALUE,DIFFERENCE_VALUE,TOLERANCE_VALUE,STATUS,DETAILS)
    VALUES
      (:RUN_ID,'clinical_tool_current_count',:RAW_CURRENT,:CORE_CURRENT,:RAW_CURRENT-:CORE_CURRENT,0,IFF(:RAW_CURRENT=:CORE_CURRENT,'PASS','FAIL'),OBJECT_CONSTRUCT()),
      (:RUN_ID,'clinical_tool_duplicate_current_versions',0,:DUP_CURRENT,0-:DUP_CURRENT,0,IFF(:DUP_CURRENT=0,'PASS','FAIL'),OBJECT_CONSTRUCT()),
      (:RUN_ID,'clinical_tool_missing_current_names',0,:MISSING_NAMES,0-:MISSING_NAMES,0,IFF(:MISSING_NAMES=0,'PASS','FAIL'),OBJECT_CONSTRUCT());

    SELECT COUNT(*) INTO :FAILURES FROM OPS.RECONCILIATION_RESULT WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';
    RETURN OBJECT_CONSTRUCT('run_id',:RUN_ID,'status',IFF(:FAILURES=0,'PASS','FAIL'),'failed_controls',:FAILURES);
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.RECONCILE_QUALITY_RATINGS(RUN_ID STRING)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE INVALID_COMPONENT_SUM NUMBER; OUT_OF_RANGE NUMBER; ORPHAN_TOOLS NUMBER; FAILURES NUMBER;
BEGIN
    SELECT COUNT(*) INTO :INVALID_COMPONENT_SUM
    FROM CORE.FCT_QUALITY_RATING
    WHERE ABS(OVERALL_SCORE-(SCIENTIFIC_SOUNDNESS_SCORE+IMPORTANCE_SCORE+USABILITY_FEASIBILITY_SCORE))>0.01;

    SELECT COUNT(*) INTO :OUT_OF_RANGE
    FROM CORE.FCT_QUALITY_RATING
    WHERE OVERALL_SCORE NOT BETWEEN 0 AND 10
       OR SCIENTIFIC_SOUNDNESS_SCORE NOT BETWEEN 0 AND 6
       OR IMPORTANCE_SCORE NOT BETWEEN 0 AND 3
       OR USABILITY_FEASIBILITY_SCORE NOT BETWEEN 0 AND 1;

    SELECT COUNT(*) INTO :ORPHAN_TOOLS
    FROM CORE.FCT_QUALITY_RATING R
    LEFT JOIN CORE.DIM_CLINICAL_TOOL T ON R.CLINICAL_TOOL_KEY=T.CLINICAL_TOOL_KEY
    WHERE R.CLINICAL_TOOL_KEY IS NOT NULL AND T.CLINICAL_TOOL_KEY IS NULL;

    INSERT INTO OPS.RECONCILIATION_RESULT(RUN_ID,CONTROL_NAME,SOURCE_VALUE,TARGET_VALUE,DIFFERENCE_VALUE,TOLERANCE_VALUE,STATUS,DETAILS)
    VALUES
      (:RUN_ID,'quality_rating_component_sum',0,:INVALID_COMPONENT_SUM,0-:INVALID_COMPONENT_SUM,0,IFF(:INVALID_COMPONENT_SUM=0,'PASS','FAIL'),OBJECT_CONSTRUCT()),
      (:RUN_ID,'quality_rating_ranges',0,:OUT_OF_RANGE,0-:OUT_OF_RANGE,0,IFF(:OUT_OF_RANGE=0,'PASS','FAIL'),OBJECT_CONSTRUCT()),
      (:RUN_ID,'quality_rating_tool_fk',0,:ORPHAN_TOOLS,0-:ORPHAN_TOOLS,0,IFF(:ORPHAN_TOOLS=0,'PASS','FAIL'),OBJECT_CONSTRUCT());

    SELECT COUNT(*) INTO :FAILURES FROM OPS.RECONCILIATION_RESULT WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';
    RETURN OBJECT_CONSTRUCT('run_id',:RUN_ID,'status',IFF(:FAILURES=0,'PASS','FAIL'),'failed_controls',:FAILURES);
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.PUBLISHABILITY_GATE(RUN_ID STRING)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE RUN_STATUS STRING; FAILED_RECON NUMBER; FAILED_QUALITY NUMBER; UNEXPLAINED NUMBER;
BEGIN
    SELECT STATUS, SOURCE_COUNT-(INSERTED_COUNT+UPDATED_COUNT+DUPLICATE_COUNT+STALE_COUNT+UNCHANGED_COUNT+QUARANTINED_COUNT)
      INTO :RUN_STATUS,:UNEXPLAINED
    FROM OPS.PIPELINE_RUN WHERE RUN_ID=:RUN_ID;

    SELECT COUNT(*) INTO :FAILED_RECON FROM OPS.RECONCILIATION_RESULT WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';
    SELECT COUNT(*) INTO :FAILED_QUALITY FROM OPS.DATA_QUALITY_RESULT
      WHERE RUN_ID=:RUN_ID AND STATUS='FAIL' AND UPPER(SEVERITY) IN ('ERROR','CRITICAL');

    RETURN OBJECT_CONSTRUCT(
      'run_id',:RUN_ID,
      'run_status',:RUN_STATUS,
      'failed_reconciliation',:FAILED_RECON,
      'failed_quality',:FAILED_QUALITY,
      'unexplained_rows',:UNEXPLAINED,
      'publishable',IFF(:RUN_STATUS IN ('RUNNING','SUCCESS') AND :FAILED_RECON=0 AND :FAILED_QUALITY=0 AND :UNEXPLAINED=0,TRUE,FALSE)
    );
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.COMMIT_WATERMARK(
    RUN_ID STRING,
    PIPELINE_NAME STRING,
    SOURCE_NAME STRING,
    WATERMARK_NAME STRING,
    WATERMARK_TS TIMESTAMP_TZ
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE FAILED_CONTROLS NUMBER; FAILED_QUALITY NUMBER; RUN_STATUS STRING; CURRENT_WATERMARK TIMESTAMP_TZ;
BEGIN
    SELECT STATUS INTO :RUN_STATUS FROM OPS.PIPELINE_RUN WHERE RUN_ID=:RUN_ID;
    SELECT COUNT(*) INTO :FAILED_CONTROLS FROM OPS.RECONCILIATION_RESULT WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';
    SELECT COUNT(*) INTO :FAILED_QUALITY FROM OPS.DATA_QUALITY_RESULT
      WHERE RUN_ID=:RUN_ID AND STATUS='FAIL' AND UPPER(SEVERITY) IN ('ERROR','CRITICAL');
    SELECT MAX(WATERMARK_TS) INTO :CURRENT_WATERMARK FROM OPS.WATERMARK
      WHERE PIPELINE_NAME=:PIPELINE_NAME AND SOURCE_NAME=:SOURCE_NAME AND WATERMARK_NAME=:WATERMARK_NAME;

    IF (:RUN_STATUS <> 'RUNNING') THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','run_not_running','run_status',:RUN_STATUS);
    END IF;
    IF (:FAILED_CONTROLS > 0) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','reconciliation_failed','failed_controls',:FAILED_CONTROLS);
    END IF;
    IF (:FAILED_QUALITY > 0) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','quality_failed','failed_quality_checks',:FAILED_QUALITY);
    END IF;
    IF (:CURRENT_WATERMARK IS NOT NULL AND :WATERMARK_TS < :CURRENT_WATERMARK) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','watermark_regression','current',:CURRENT_WATERMARK,'candidate',:WATERMARK_TS);
    END IF;

    MERGE INTO OPS.WATERMARK T
    USING (SELECT :PIPELINE_NAME PIPELINE_NAME,:SOURCE_NAME SOURCE_NAME,:WATERMARK_NAME WATERMARK_NAME,:WATERMARK_TS WATERMARK_TS) S
    ON T.PIPELINE_NAME=S.PIPELINE_NAME AND T.SOURCE_NAME=S.SOURCE_NAME AND T.WATERMARK_NAME=S.WATERMARK_NAME
    WHEN MATCHED THEN UPDATE SET T.WATERMARK_TS=S.WATERMARK_TS,T.UPDATED_AT=CURRENT_TIMESTAMP(),T.UPDATED_BY_RUN_ID=:RUN_ID
    WHEN NOT MATCHED THEN INSERT (PIPELINE_NAME,SOURCE_NAME,WATERMARK_NAME,WATERMARK_TS,UPDATED_AT,UPDATED_BY_RUN_ID)
      VALUES (S.PIPELINE_NAME,S.SOURCE_NAME,S.WATERMARK_NAME,S.WATERMARK_TS,CURRENT_TIMESTAMP(),:RUN_ID);

    RETURN OBJECT_CONSTRUCT('status','COMMITTED','watermark_ts',:WATERMARK_TS,'run_id',:RUN_ID);
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.MARK_QUARANTINE_FOR_REPLAY(
    SOURCE_RUN_ID STRING,
    REASON_CODE STRING,
    MAX_ROWS NUMBER
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE MARKED NUMBER;
BEGIN
    UPDATE OPS.QUARANTINE_EVENT
    SET REPLAY_STATUS='READY',
        ERROR_MESSAGE=COALESCE(ERROR_MESSAGE,'') || ' | replay_reason=' || :REASON_CODE
    WHERE QUARANTINE_ID IN (
      SELECT QUARANTINE_ID FROM OPS.QUARANTINE_EVENT
      WHERE RUN_ID=:SOURCE_RUN_ID AND REPLAY_STATUS='PENDING'
      ORDER BY QUARANTINED_AT
      LIMIT :MAX_ROWS
    );
    MARKED := SQLROWCOUNT;
    RETURN OBJECT_CONSTRUCT('source_run_id',:SOURCE_RUN_ID,'marked_rows',:MARKED,'replay_status','READY');
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.COMPLETE_PIPELINE_RUN(
    RUN_ID STRING,
    STATUS STRING,
    SOURCE_COUNT NUMBER,
    ACCEPTED_COUNT NUMBER,
    QUARANTINED_COUNT NUMBER,
    INSERTED_COUNT NUMBER,
    UPDATED_COUNT NUMBER,
    DUPLICATE_COUNT NUMBER,
    STALE_COUNT NUMBER,
    UNCHANGED_COUNT NUMBER,
    PUBLISHED_COUNT NUMBER,
    ERROR_CLASS STRING,
    ERROR_MESSAGE STRING
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE EXPLAINED NUMBER; FAILED_CONTROLS NUMBER; FAILED_QUALITY NUMBER;
BEGIN
    EXPLAINED := :INSERTED_COUNT+:UPDATED_COUNT+:DUPLICATE_COUNT+:STALE_COUNT+:UNCHANGED_COUNT+:QUARANTINED_COUNT;
    SELECT COUNT(*) INTO :FAILED_CONTROLS FROM OPS.RECONCILIATION_RESULT WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';
    SELECT COUNT(*) INTO :FAILED_QUALITY FROM OPS.DATA_QUALITY_RESULT
      WHERE RUN_ID=:RUN_ID AND STATUS='FAIL' AND UPPER(SEVERITY) IN ('ERROR','CRITICAL');

    IF (:STATUS='SUCCESS' AND :SOURCE_COUNT <> :EXPLAINED) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','terminal_outcome_mismatch','source_count',:SOURCE_COUNT,'explained_count',:EXPLAINED);
    END IF;
    IF (:STATUS='SUCCESS' AND (:FAILED_CONTROLS>0 OR :FAILED_QUALITY>0)) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','quality_or_reconciliation_failed','failed_controls',:FAILED_CONTROLS,'failed_quality',:FAILED_QUALITY);
    END IF;

    UPDATE OPS.PIPELINE_RUN
    SET COMPLETED_AT=CURRENT_TIMESTAMP(),STATUS=:STATUS,SOURCE_COUNT=:SOURCE_COUNT,ACCEPTED_COUNT=:ACCEPTED_COUNT,
        QUARANTINED_COUNT=:QUARANTINED_COUNT,INSERTED_COUNT=:INSERTED_COUNT,UPDATED_COUNT=:UPDATED_COUNT,
        DUPLICATE_COUNT=:DUPLICATE_COUNT,STALE_COUNT=:STALE_COUNT,UNCHANGED_COUNT=:UNCHANGED_COUNT,
        PUBLISHED_COUNT=:PUBLISHED_COUNT,ERROR_CLASS=:ERROR_CLASS,ERROR_MESSAGE=:ERROR_MESSAGE
    WHERE RUN_ID=:RUN_ID;

    RETURN OBJECT_CONSTRUCT('run_id',:RUN_ID,'status',:STATUS,'source_count',:SOURCE_COUNT,
      'explained_count',:EXPLAINED,'failed_controls',:FAILED_CONTROLS,'failed_quality',:FAILED_QUALITY);
END;
$$;
