-- Transactional warehouse procedures for deterministic publication and run controls.

USE DATABASE CLINICAL_ANALYTICS;

CREATE OR REPLACE PROCEDURE OPS.BEGIN_PIPELINE_RUN(
    RUN_ID STRING,
    PIPELINE_NAME STRING,
    WATERMARK_LOW TIMESTAMP_TZ,
    WATERMARK_HIGH TIMESTAMP_TZ,
    QUERY_TAG STRING,
    GIT_SHA STRING
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO OPS.PIPELINE_RUN T
    USING (
      SELECT
        :RUN_ID RUN_ID,
        :PIPELINE_NAME PIPELINE_NAME,
        :WATERMARK_LOW WATERMARK_LOW,
        :WATERMARK_HIGH WATERMARK_HIGH,
        :QUERY_TAG QUERY_TAG,
        :GIT_SHA GIT_SHA
    ) S
    ON T.RUN_ID=S.RUN_ID
    WHEN MATCHED THEN UPDATE SET
      T.PIPELINE_NAME=S.PIPELINE_NAME,
      T.STARTED_AT=CURRENT_TIMESTAMP(),
      T.COMPLETED_AT=NULL,
      T.STATUS='RUNNING',
      T.SOURCE_WATERMARK_LOW=S.WATERMARK_LOW,
      T.SOURCE_WATERMARK_HIGH=S.WATERMARK_HIGH,
      T.QUERY_TAG=S.QUERY_TAG,
      T.GIT_SHA=S.GIT_SHA,
      T.ERROR_CLASS=NULL,
      T.ERROR_MESSAGE=NULL
    WHEN NOT MATCHED THEN INSERT (
      RUN_ID,PIPELINE_NAME,STARTED_AT,STATUS,SOURCE_WATERMARK_LOW,
      SOURCE_WATERMARK_HIGH,QUERY_TAG,GIT_SHA
    ) VALUES (
      S.RUN_ID,S.PIPELINE_NAME,CURRENT_TIMESTAMP(),'RUNNING',S.WATERMARK_LOW,
      S.WATERMARK_HIGH,S.QUERY_TAG,S.GIT_SHA
    );

    RETURN OBJECT_CONSTRUCT(
      'run_id', :RUN_ID,
      'status', 'RUNNING',
      'started_at', CURRENT_TIMESTAMP()
    );
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.RECORD_QUALITY_RESULT(
    RUN_ID STRING,
    MODEL_NAME STRING,
    TEST_NAME STRING,
    SEVERITY STRING,
    STATUS STRING,
    FAILED_ROWS NUMBER,
    TOTAL_ROWS NUMBER,
    DETAILS VARIANT
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    FAILURE_RATIO FLOAT;
BEGIN
    FAILURE_RATIO := IFF(:TOTAL_ROWS=0,0,:FAILED_ROWS/:TOTAL_ROWS);

    MERGE INTO OPS.DATA_QUALITY_RESULT T
    USING (
      SELECT :RUN_ID RUN_ID,:MODEL_NAME MODEL_NAME,:TEST_NAME TEST_NAME
    ) S
    ON T.RUN_ID=S.RUN_ID AND T.MODEL_NAME=S.MODEL_NAME AND T.TEST_NAME=S.TEST_NAME
    WHEN MATCHED THEN UPDATE SET
      SEVERITY=:SEVERITY,
      STATUS=:STATUS,
      FAILED_ROWS=:FAILED_ROWS,
      TOTAL_ROWS=:TOTAL_ROWS,
      FAILURE_RATIO=:FAILURE_RATIO,
      OBSERVED_AT=CURRENT_TIMESTAMP(),
      DETAILS=:DETAILS
    WHEN NOT MATCHED THEN INSERT (
      RUN_ID,MODEL_NAME,TEST_NAME,SEVERITY,STATUS,FAILED_ROWS,TOTAL_ROWS,
      FAILURE_RATIO,OBSERVED_AT,DETAILS
    ) VALUES (
      :RUN_ID,:MODEL_NAME,:TEST_NAME,:SEVERITY,:STATUS,:FAILED_ROWS,:TOTAL_ROWS,
      :FAILURE_RATIO,CURRENT_TIMESTAMP(),:DETAILS
    );

    RETURN OBJECT_CONSTRUCT(
      'run_id',:RUN_ID,
      'model_name',:MODEL_NAME,
      'test_name',:TEST_NAME,
      'status',:STATUS,
      'failure_ratio',:FAILURE_RATIO
    );
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.RECONCILE_PRODUCT_EVENT_WINDOW(
    RUN_ID STRING,
    WINDOW_LOW TIMESTAMP_TZ,
    WINDOW_HIGH TIMESTAMP_TZ
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    RAW_COUNT NUMBER;
    STAGED_COUNT NUMBER;
    CORE_COUNT NUMBER;
    RAW_DISTINCT NUMBER;
    STAGED_DISTINCT NUMBER;
    CORE_DISTINCT NUMBER;
    RAW_COMPLETIONS NUMBER;
    CORE_COMPLETIONS NUMBER;
    FAILURES NUMBER DEFAULT 0;
BEGIN
    SELECT COUNT(*),COUNT(DISTINCT EVENT_ID),COUNT_IF(EVENT_TYPE='tool_complete')
      INTO :RAW_COUNT,:RAW_DISTINCT,:RAW_COMPLETIONS
    FROM RAW.PRODUCT_EVENT
    WHERE EVENT_TS >= :WINDOW_LOW AND EVENT_TS < :WINDOW_HIGH;

    SELECT COUNT(*),COUNT(DISTINCT EVENT_ID)
      INTO :STAGED_COUNT,:STAGED_DISTINCT
    FROM STAGING.PRODUCT_EVENT
    WHERE EVENT_TS >= :WINDOW_LOW AND EVENT_TS < :WINDOW_HIGH;

    SELECT COUNT(*),COUNT(DISTINCT EVENT_ID),COUNT_IF(EVENT_TYPE='tool_complete')
      INTO :CORE_COUNT,:CORE_DISTINCT,:CORE_COMPLETIONS
    FROM CORE.FCT_PRODUCT_EVENT
    WHERE EVENT_TS >= :WINDOW_LOW AND EVENT_TS < :WINDOW_HIGH;

    DELETE FROM OPS.RECONCILIATION_RESULT
    WHERE RUN_ID=:RUN_ID
      AND CONTROL_NAME IN (
        'raw_to_staging_distinct_events',
        'staging_to_core_distinct_events',
        'tool_completion_count'
      );

    INSERT INTO OPS.RECONCILIATION_RESULT(
      RUN_ID,CONTROL_NAME,SOURCE_VALUE,TARGET_VALUE,DIFFERENCE_VALUE,
      TOLERANCE_VALUE,STATUS,DETAILS
    ) VALUES
      (
        :RUN_ID,'raw_to_staging_distinct_events',:RAW_DISTINCT,:STAGED_DISTINCT,
        :RAW_DISTINCT-:STAGED_DISTINCT,0,
        IFF(:RAW_DISTINCT=:STAGED_DISTINCT,'PASS','FAIL'),
        OBJECT_CONSTRUCT('window_low',:WINDOW_LOW,'window_high',:WINDOW_HIGH,
                         'raw_rows',:RAW_COUNT,'staged_rows',:STAGED_COUNT)
      ),
      (
        :RUN_ID,'staging_to_core_distinct_events',:STAGED_DISTINCT,:CORE_DISTINCT,
        :STAGED_DISTINCT-:CORE_DISTINCT,0,
        IFF(:STAGED_DISTINCT=:CORE_DISTINCT,'PASS','FAIL'),
        OBJECT_CONSTRUCT('window_low',:WINDOW_LOW,'window_high',:WINDOW_HIGH,
                         'staged_rows',:STAGED_COUNT,'core_rows',:CORE_COUNT)
      ),
      (
        :RUN_ID,'tool_completion_count',:RAW_COMPLETIONS,:CORE_COMPLETIONS,
        :RAW_COMPLETIONS-:CORE_COMPLETIONS,0,
        IFF(:RAW_COMPLETIONS=:CORE_COMPLETIONS,'PASS','FAIL'),
        OBJECT_CONSTRUCT('event_type','tool_complete')
      );

    SELECT COUNT(*) INTO :FAILURES
    FROM OPS.RECONCILIATION_RESULT
    WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';

    RETURN OBJECT_CONSTRUCT(
      'run_id',:RUN_ID,
      'raw_count',:RAW_COUNT,
      'staging_count',:STAGED_COUNT,
      'core_count',:CORE_COUNT,
      'failed_controls',:FAILURES,
      'status',IFF(:FAILURES=0,'PASS','FAIL')
    );
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.COMMIT_WATERMARK(
    RUN_ID STRING,
    PIPELINE_NAME STRING,
    SOURCE_NAME STRING,
    WATERMARK_NAME STRING,
    WATERMARK_TS TIMESTAMP_TZ
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    FAILED_CONTROLS NUMBER;
    FAILED_QUALITY NUMBER;
    RUN_STATUS STRING;
BEGIN
    SELECT STATUS INTO :RUN_STATUS
    FROM OPS.PIPELINE_RUN
    WHERE RUN_ID=:RUN_ID;

    SELECT COUNT(*) INTO :FAILED_CONTROLS
    FROM OPS.RECONCILIATION_RESULT
    WHERE RUN_ID=:RUN_ID AND STATUS='FAIL';

    SELECT COUNT(*) INTO :FAILED_QUALITY
    FROM OPS.DATA_QUALITY_RESULT
    WHERE RUN_ID=:RUN_ID AND STATUS='FAIL' AND UPPER(SEVERITY) IN ('ERROR','CRITICAL');

    IF (:RUN_STATUS <> 'RUNNING') THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','run_not_running','run_status',:RUN_STATUS);
    END IF;

    IF (:FAILED_CONTROLS > 0) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','reconciliation_failed','failed_controls',:FAILED_CONTROLS);
    END IF;

    IF (:FAILED_QUALITY > 0) THEN
      RETURN OBJECT_CONSTRUCT('status','REJECTED','reason','quality_failed','failed_quality_checks',:FAILED_QUALITY);
    END IF;

    MERGE INTO OPS.WATERMARK T
    USING (
      SELECT :PIPELINE_NAME PIPELINE_NAME,:SOURCE_NAME SOURCE_NAME,
             :WATERMARK_NAME WATERMARK_NAME,:WATERMARK_TS WATERMARK_TS
    ) S
    ON T.PIPELINE_NAME=S.PIPELINE_NAME
      AND T.SOURCE_NAME=S.SOURCE_NAME
      AND T.WATERMARK_NAME=S.WATERMARK_NAME
    WHEN MATCHED AND S.WATERMARK_TS >= T.WATERMARK_TS THEN UPDATE SET
      T.WATERMARK_TS=S.WATERMARK_TS,
      T.UPDATED_AT=CURRENT_TIMESTAMP(),
      T.UPDATED_BY_RUN_ID=:RUN_ID
    WHEN NOT MATCHED THEN INSERT (
      PIPELINE_NAME,SOURCE_NAME,WATERMARK_NAME,WATERMARK_TS,UPDATED_AT,UPDATED_BY_RUN_ID
    ) VALUES (
      S.PIPELINE_NAME,S.SOURCE_NAME,S.WATERMARK_NAME,S.WATERMARK_TS,CURRENT_TIMESTAMP(),:RUN_ID
    );

    RETURN OBJECT_CONSTRUCT(
      'status','COMMITTED',
      'watermark_ts',:WATERMARK_TS,
      'run_id',:RUN_ID
    );
END;
$$;

CREATE OR REPLACE PROCEDURE OPS.COMPLETE_PIPELINE_RUN(
    RUN_ID STRING,
    STATUS STRING,
    SOURCE_COUNT NUMBER,
    ACCEPTED_COUNT NUMBER,
    QUARANTINED_COUNT NUMBER,
    INSERTED_COUNT NUMBER,
    UPDATED_COUNT NUMBER,
    DUPLICATE_COUNT NUMBER,
    STALE_COUNT NUMBER,
    UNCHANGED_COUNT NUMBER,
    PUBLISHED_COUNT NUMBER,
    ERROR_CLASS STRING,
    ERROR_MESSAGE STRING
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    EXPLAINED NUMBER;
BEGIN
    EXPLAINED := :INSERTED_COUNT+:UPDATED_COUNT+:DUPLICATE_COUNT+:STALE_COUNT+:UNCHANGED_COUNT+:QUARANTINED_COUNT;

    IF (:STATUS='SUCCESS' AND :SOURCE_COUNT <> :EXPLAINED) THEN
      RETURN OBJECT_CONSTRUCT(
        'status','REJECTED',
        'reason','terminal_outcome_mismatch',
        'source_count',:SOURCE_COUNT,
        'explained_count',:EXPLAINED
      );
    END IF;

    UPDATE OPS.PIPELINE_RUN
    SET COMPLETED_AT=CURRENT_TIMESTAMP(),
        STATUS=:STATUS,
        SOURCE_COUNT=:SOURCE_COUNT,
        ACCEPTED_COUNT=:ACCEPTED_COUNT,
        QUARANTINED_COUNT=:QUARANTINED_COUNT,
        INSERTED_COUNT=:INSERTED_COUNT,
        UPDATED_COUNT=:UPDATED_COUNT,
        DUPLICATE_COUNT=:DUPLICATE_COUNT,
        STALE_COUNT=:STALE_COUNT,
        UNCHANGED_COUNT=:UNCHANGED_COUNT,
        PUBLISHED_COUNT=:PUBLISHED_COUNT,
        ERROR_CLASS=:ERROR_CLASS,
        ERROR_MESSAGE=:ERROR_MESSAGE
    WHERE RUN_ID=:RUN_ID;

    RETURN OBJECT_CONSTRUCT(
      'run_id',:RUN_ID,
      'status',:STATUS,
      'source_count',:SOURCE_COUNT,
      'explained_count',:EXPLAINED
    );
END;
$$;
