-- Snowflake access model for the clinical data platform.
-- Roles are separated by operational duty so ingestion, transformation, analytics,
-- observability, and administration do not share a single broad privilege set.

USE DATABASE CLINICAL_ANALYTICS;

CREATE ROLE IF NOT EXISTS CDP_INGEST_ROLE COMMENT='Writes immutable RAW data and pipeline audit metadata';
CREATE ROLE IF NOT EXISTS CDP_TRANSFORM_ROLE COMMENT='Reads RAW/STAGING and writes canonical CORE/MART models';
CREATE ROLE IF NOT EXISTS CDP_ANALYTICS_ROLE COMMENT='Read-only access to approved MART and selected CORE objects';
CREATE ROLE IF NOT EXISTS CDP_OBSERVABILITY_ROLE COMMENT='Read operational controls, query history, and health views';
CREATE ROLE IF NOT EXISTS CDP_GOVERNANCE_ROLE COMMENT='Manage ownership metadata, classifications, and approved policies';
CREATE ROLE IF NOT EXISTS CDP_SERVICE_ROLE COMMENT='Parent role for non-human platform services';
CREATE ROLE IF NOT EXISTS CDP_ENGINEER_ROLE COMMENT='Engineering read access plus controlled development schemas';
CREATE ROLE IF NOT EXISTS CDP_ADMIN_ROLE COMMENT='Platform administration role below ACCOUNTADMIN';

-- Role hierarchy.
GRANT ROLE CDP_INGEST_ROLE TO ROLE CDP_SERVICE_ROLE;
GRANT ROLE CDP_TRANSFORM_ROLE TO ROLE CDP_SERVICE_ROLE;
GRANT ROLE CDP_OBSERVABILITY_ROLE TO ROLE CDP_ENGINEER_ROLE;
GRANT ROLE CDP_ANALYTICS_ROLE TO ROLE CDP_ENGINEER_ROLE;
GRANT ROLE CDP_SERVICE_ROLE TO ROLE CDP_ADMIN_ROLE;
GRANT ROLE CDP_ENGINEER_ROLE TO ROLE CDP_ADMIN_ROLE;
GRANT ROLE CDP_GOVERNANCE_ROLE TO ROLE CDP_ADMIN_ROLE;

-- Database visibility.
GRANT USAGE ON DATABASE CLINICAL_ANALYTICS TO ROLE CDP_INGEST_ROLE;
GRANT USAGE ON DATABASE CLINICAL_ANALYTICS TO ROLE CDP_TRANSFORM_ROLE;
GRANT USAGE ON DATABASE CLINICAL_ANALYTICS TO ROLE CDP_ANALYTICS_ROLE;
GRANT USAGE ON DATABASE CLINICAL_ANALYTICS TO ROLE CDP_OBSERVABILITY_ROLE;
GRANT USAGE ON DATABASE CLINICAL_ANALYTICS TO ROLE CDP_GOVERNANCE_ROLE;
GRANT USAGE ON DATABASE CLINICAL_ANALYTICS TO ROLE CDP_ENGINEER_ROLE;

-- Ingestion privileges.
GRANT USAGE ON SCHEMA RAW TO ROLE CDP_INGEST_ROLE;
GRANT USAGE ON SCHEMA OPS TO ROLE CDP_INGEST_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE CDP_INGEST_ROLE;
GRANT INSERT, SELECT, UPDATE ON OPS.PIPELINE_RUN TO ROLE CDP_INGEST_ROLE;
GRANT INSERT, SELECT, UPDATE ON OPS.WATERMARK TO ROLE CDP_INGEST_ROLE;
GRANT INSERT, SELECT, UPDATE ON OPS.QUARANTINE_EVENT TO ROLE CDP_INGEST_ROLE;
GRANT INSERT, SELECT ON OPS.DATA_QUALITY_RESULT TO ROLE CDP_INGEST_ROLE;
GRANT INSERT, SELECT ON OPS.RECONCILIATION_RESULT TO ROLE CDP_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE CDP_INGEST_ROLE;

-- Future ingestion objects inherit the same narrow capability.
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE CDP_INGEST_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA RAW TO ROLE CDP_INGEST_ROLE;
GRANT READ ON FUTURE STAGES IN SCHEMA RAW TO ROLE CDP_INGEST_ROLE;

-- Transformation privileges.
GRANT USAGE ON SCHEMA RAW TO ROLE CDP_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA STAGING TO ROLE CDP_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA CORE TO ROLE CDP_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA MART TO ROLE CDP_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA OPS TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CORE TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MART TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA OPS TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO ROLE CDP_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE CDP_TRANSFORM_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA OPS TO ROLE CDP_TRANSFORM_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STAGING TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CORE TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MART TO ROLE CDP_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO ROLE CDP_TRANSFORM_ROLE;

-- Analytics privileges intentionally exclude RAW and pseudonymous control tables.
GRANT USAGE ON SCHEMA MART TO ROLE CDP_ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA CORE TO ROLE CDP_ANALYTICS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO ROLE CDP_ANALYTICS_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO ROLE CDP_ANALYTICS_ROLE;
GRANT SELECT ON CORE.DIM_CLINICAL_TOOL TO ROLE CDP_ANALYTICS_ROLE;
GRANT SELECT ON CORE.DIM_CONTENT TO ROLE CDP_ANALYTICS_ROLE;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE CDP_ANALYTICS_ROLE;

-- Observability role can inspect platform controls without modifying business data.
GRANT USAGE ON SCHEMA OPS TO ROLE CDP_OBSERVABILITY_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA OPS TO ROLE CDP_OBSERVABILITY_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA OPS TO ROLE CDP_OBSERVABILITY_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPS TO ROLE CDP_OBSERVABILITY_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA OPS TO ROLE CDP_OBSERVABILITY_ROLE;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE CDP_OBSERVABILITY_ROLE;

-- Governance metadata is maintained independently from transformation code.
GRANT USAGE ON SCHEMA GOVERNANCE TO ROLE CDP_GOVERNANCE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GOVERNANCE TO ROLE CDP_GOVERNANCE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE TO ROLE CDP_GOVERNANCE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GOVERNANCE TO ROLE CDP_GOVERNANCE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNANCE TO ROLE CDP_GOVERNANCE_ROLE;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE CDP_GOVERNANCE_ROLE;

-- Engineer role is read-heavy in production. Write privileges belong in environment-specific
-- development schemas, not in production CORE/MART.
GRANT USAGE ON SCHEMA RAW TO ROLE CDP_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA STAGING TO ROLE CDP_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA CORE TO ROLE CDP_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA MART TO ROLE CDP_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA OPS TO ROLE CDP_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE CDP_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA STAGING TO ROLE CDP_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE CDP_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO ROLE CDP_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA OPS TO ROLE CDP_ENGINEER_ROLE;

-- Warehouse ownership remains with the platform admin role. Service roles get USAGE only.
GRANT OWNERSHIP ON WAREHOUSE INGEST_WH TO ROLE CDP_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE TRANSFORM_WH TO ROLE CDP_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE BI_WH TO ROLE CDP_ADMIN_ROLE COPY CURRENT GRANTS;

-- Session defaults reduce accidental expensive scans and improve attribution.
ALTER WAREHOUSE INGEST_WH SET STATEMENT_TIMEOUT_IN_SECONDS=1800;
ALTER WAREHOUSE TRANSFORM_WH SET STATEMENT_TIMEOUT_IN_SECONDS=3600;
ALTER WAREHOUSE BI_WH SET STATEMENT_TIMEOUT_IN_SECONDS=600;

-- Network policies, user assignments, SSO groups, storage integrations, and masking policy
-- bindings are environment-specific and are deliberately applied by deployment automation.
