-- Warehouse performance diagnostics and tuning reference.
-- Queries are read-only except for explicit optimization statements near the bottom.

USE DATABASE CLINICAL_ANALYTICS;

-- Recent expensive queries attributed to this platform.
CREATE OR REPLACE VIEW OPS.V_EXPENSIVE_PLATFORM_QUERIES AS
SELECT
    QUERY_ID,
    QUERY_TEXT,
    QUERY_TAG,
    USER_NAME,
    ROLE_NAME,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME/1000 AS ELAPSED_SECONDS,
    BYTES_SCANNED,
    BYTES_WRITTEN,
    BYTES_SPILLED_TO_LOCAL_STORAGE,
    BYTES_SPILLED_TO_REMOTE_STORAGE,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    ROWS_PRODUCED,
    CREDITS_USED_CLOUD_SERVICES,
    QUEUED_OVERLOAD_TIME/1000 AS QUEUED_OVERLOAD_SECONDS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-7,CURRENT_TIMESTAMP())
  AND QUERY_TAG ILIKE 'clinical-data-platform%'
  AND EXECUTION_STATUS='SUCCESS'
ORDER BY TOTAL_ELAPSED_TIME DESC;

-- Partition pruning effectiveness. A high scanned/total ratio on selective analytical
-- queries is a signal to review clustering keys, predicate shapes, or model grain.
CREATE OR REPLACE VIEW OPS.V_PARTITION_PRUNING AS
SELECT
    QUERY_ID,
    WAREHOUSE_NAME,
    START_TIME,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    DIV0(PARTITIONS_SCANNED,PARTITIONS_TOTAL) AS PARTITION_SCAN_RATIO,
    BYTES_SCANNED,
    TOTAL_ELAPSED_TIME/1000 AS ELAPSED_SECONDS,
    QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-7,CURRENT_TIMESTAMP())
  AND QUERY_TAG ILIKE 'clinical-data-platform%'
  AND PARTITIONS_TOTAL>0;

-- Warehouse queue pressure indicates compute contention rather than inefficient SQL alone.
CREATE OR REPLACE VIEW OPS.V_WAREHOUSE_QUEUE_PRESSURE AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('hour',START_TIME) AS HOUR,
    COUNT(*) AS QUERY_COUNT,
    AVG(QUEUED_OVERLOAD_TIME)/1000 AS AVG_OVERLOAD_QUEUE_SECONDS,
    MAX(QUEUED_OVERLOAD_TIME)/1000 AS MAX_OVERLOAD_QUEUE_SECONDS,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_ELAPSED_SECONDS,
    APPROX_PERCENTILE(TOTAL_ELAPSED_TIME/1000,0.95) AS P95_ELAPSED_SECONDS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-7,CURRENT_TIMESTAMP())
  AND QUERY_TAG ILIKE 'clinical-data-platform%'
GROUP BY 1,2;

-- Model-level storage footprint.
CREATE OR REPLACE VIEW OPS.V_TABLE_STORAGE_PROFILE AS
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    ACTIVE_BYTES,
    TIME_TRAVEL_BYTES,
    FAILSAFE_BYTES,
    RETAINED_FOR_CLONE_BYTES,
    TABLE_CREATED,
    TABLE_DROPPED
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG='CLINICAL_ANALYTICS'
ORDER BY ACTIVE_BYTES DESC;

-- Search for repeated full scans of the canonical event fact.
CREATE OR REPLACE VIEW OPS.V_PRODUCT_EVENT_SCAN_PROFILE AS
SELECT
    DATE_TRUNC('day',START_TIME) AS QUERY_DATE,
    WAREHOUSE_NAME,
    COUNT(*) AS QUERY_COUNT,
    SUM(BYTES_SCANNED) AS TOTAL_BYTES_SCANNED,
    AVG(BYTES_SCANNED) AS AVG_BYTES_SCANNED,
    APPROX_PERCENTILE(BYTES_SCANNED,0.95) AS P95_BYTES_SCANNED,
    AVG(PARTITIONS_SCANNED) AS AVG_PARTITIONS_SCANNED,
    AVG(PARTITIONS_TOTAL) AS AVG_PARTITIONS_TOTAL
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-30,CURRENT_TIMESTAMP())
  AND QUERY_TEXT ILIKE '%CORE.FCT_PRODUCT_EVENT%'
  AND EXECUTION_STATUS='SUCCESS'
GROUP BY 1,2;

-- Useful cardinality and skew checks before choosing clustering or aggregate design.
SELECT
    COUNT(*) AS ROWS,
    COUNT(DISTINCT EVENT_DATE) AS EVENT_DATES,
    COUNT(DISTINCT EVENT_TYPE) AS EVENT_TYPES,
    COUNT(DISTINCT CLINICAL_TOOL_KEY) AS TOOLS,
    COUNT(DISTINCT ACCOUNT_KEY) AS ACCOUNTS,
    COUNT(DISTINCT USER_TOKEN) AS USERS,
    COUNT(DISTINCT SESSION_ID) AS SESSIONS
FROM CORE.FCT_PRODUCT_EVENT;

SELECT
    EVENT_TYPE,
    COUNT(*) AS ROWS,
    DIV0(COUNT(*),SUM(COUNT(*)) OVER()) AS ROW_SHARE
FROM CORE.FCT_PRODUCT_EVENT
GROUP BY EVENT_TYPE
ORDER BY ROWS DESC;

SELECT
    EVENT_DATE,
    COUNT(*) AS ROWS,
    COUNT(DISTINCT SESSION_ID) AS SESSIONS,
    COUNT(DISTINCT USER_TOKEN) AS USERS
FROM CORE.FCT_PRODUCT_EVENT
WHERE EVENT_DATE >= DATEADD('day',-30,CURRENT_DATE())
GROUP BY EVENT_DATE
ORDER BY EVENT_DATE;

-- Clustering information exposes overlap and depth. Review after enough data accumulates;
-- clustering very small tables adds maintenance cost without material query benefit.
SELECT SYSTEM$CLUSTERING_INFORMATION(
  'CLINICAL_ANALYTICS.CORE.FCT_PRODUCT_EVENT',
  '(EVENT_DATE, EVENT_TYPE)'
) AS PRODUCT_EVENT_CLUSTERING;

SELECT SYSTEM$CLUSTERING_INFORMATION(
  'CLINICAL_ANALYTICS.CORE.FCT_TOOL_COMPLETION',
  '(EVENT_DATE, CLINICAL_TOOL_KEY)'
) AS TOOL_COMPLETION_CLUSTERING;

-- Candidate clustering definitions for large, repeatedly filtered facts.
ALTER TABLE CORE.FCT_PRODUCT_EVENT CLUSTER BY (EVENT_DATE, EVENT_TYPE);
ALTER TABLE CORE.FCT_TOOL_COMPLETION CLUSTER BY (EVENT_DATE, CLINICAL_TOOL_KEY);
ALTER TABLE CORE.FCT_SESSION CLUSTER BY (SESSION_DATE, CHANNEL);

-- Result-cache-friendly semantic views avoid volatile functions in their core definitions.
-- Date filtering belongs in consuming queries rather than embedding CURRENT_DATE in every view.
CREATE OR REPLACE VIEW MART.V_TOOL_FUNNEL AS
SELECT
    EVENT_DATE,
    CLINICAL_TOOL_KEY,
    CHANNEL,
    COUNTRY_CODE,
    COUNT_IF(EVENT_TYPE='tool_view') AS VIEWS,
    COUNT_IF(EVENT_TYPE='tool_start') AS STARTS,
    COUNT_IF(EVENT_TYPE='tool_complete') AS COMPLETIONS,
    DIV0(COUNT_IF(EVENT_TYPE='tool_start'),COUNT_IF(EVENT_TYPE='tool_view')) AS START_RATE,
    DIV0(COUNT_IF(EVENT_TYPE='tool_complete'),COUNT_IF(EVENT_TYPE='tool_start')) AS COMPLETION_RATE
FROM CORE.FCT_PRODUCT_EVENT
WHERE CLINICAL_TOOL_KEY IS NOT NULL
GROUP BY 1,2,3,4;

-- Query examples shaped for pruning.
SELECT
    EVENT_DATE,
    EVENT_TYPE,
    COUNT(*) AS EVENTS
FROM CORE.FCT_PRODUCT_EVENT
WHERE EVENT_DATE BETWEEN '2026-09-01'::DATE AND '2026-09-07'::DATE
  AND EVENT_TYPE IN ('tool_view','tool_start','tool_complete')
GROUP BY 1,2
ORDER BY 1,2;

-- Avoid wrapping partition/clustering columns in functions inside predicates when a direct
-- range can express the same condition. This range form keeps micro-partition pruning visible.
SELECT COUNT(*)
FROM CORE.FCT_PRODUCT_EVENT
WHERE EVENT_TS >= '2026-09-01 00:00:00 +00:00'::TIMESTAMP_TZ
  AND EVENT_TS <  '2026-09-02 00:00:00 +00:00'::TIMESTAMP_TZ;

-- Warehouse utilization and credit trends support right-sizing decisions.
CREATE OR REPLACE VIEW OPS.V_WAREHOUSE_METERING_DAILY AS
SELECT
    START_TIME::DATE AS USAGE_DATE,
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS CREDITS_USED,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day',-30,CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME IN ('INGEST_WH','TRANSFORM_WH','BI_WH')
GROUP BY 1,2
ORDER BY 1 DESC,2;

-- Repeatedly slow query signatures can be grouped after removing literals in an external
-- analysis job. This raw view exposes query hash fields when supported by account metadata.
CREATE OR REPLACE VIEW OPS.V_QUERY_SHAPE_DAILY AS
SELECT
    START_TIME::DATE AS QUERY_DATE,
    QUERY_PARAMETERIZED_HASH,
    WAREHOUSE_NAME,
    COUNT(*) AS EXECUTIONS,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_SECONDS,
    APPROX_PERCENTILE(TOTAL_ELAPSED_TIME/1000,0.95) AS P95_SECONDS,
    SUM(BYTES_SCANNED) AS BYTES_SCANNED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-30,CURRENT_TIMESTAMP())
  AND QUERY_TAG ILIKE 'clinical-data-platform%'
GROUP BY 1,2,3;
