-- Snowflake performance engineering playbook for the clinical decision-support reference platform.
-- The diagnostic views are read-only. Explicit ALTER statements are isolated in the final section.

USE DATABASE CLINICAL_ANALYTICS;

-- -----------------------------------------------------------------------------
-- QUERY COST / LATENCY / QUEUE DIAGNOSTICS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW OPS.V_QUERY_PERFORMANCE_7D AS
SELECT
    QUERY_ID,
    QUERY_PARAMETERIZED_HASH,
    QUERY_TEXT,
    QUERY_TAG,
    USER_NAME,
    ROLE_NAME,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME/1000 AS ELAPSED_SECONDS,
    COMPILATION_TIME/1000 AS COMPILATION_SECONDS,
    EXECUTION_TIME/1000 AS EXECUTION_SECONDS,
    QUEUED_OVERLOAD_TIME/1000 AS QUEUED_OVERLOAD_SECONDS,
    QUEUED_PROVISIONING_TIME/1000 AS QUEUED_PROVISIONING_SECONDS,
    BYTES_SCANNED,
    BYTES_WRITTEN,
    BYTES_SPILLED_TO_LOCAL_STORAGE,
    BYTES_SPILLED_TO_REMOTE_STORAGE,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    DIV0(PARTITIONS_SCANNED,PARTITIONS_TOTAL) AS PARTITION_SCAN_RATIO,
    ROWS_PRODUCED,
    PERCENTAGE_SCANNED_FROM_CACHE,
    CREDITS_USED_CLOUD_SERVICES
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-7,CURRENT_TIMESTAMP())
  AND QUERY_TAG ILIKE 'clinical-data-platform%';

CREATE OR REPLACE VIEW OPS.V_EXPENSIVE_QUERY_SHAPES AS
SELECT
    QUERY_PARAMETERIZED_HASH,
    WAREHOUSE_NAME,
    COUNT(*) AS EXECUTIONS,
    AVG(ELAPSED_SECONDS) AS AVG_SECONDS,
    APPROX_PERCENTILE(ELAPSED_SECONDS,0.50) AS P50_SECONDS,
    APPROX_PERCENTILE(ELAPSED_SECONDS,0.95) AS P95_SECONDS,
    APPROX_PERCENTILE(BYTES_SCANNED,0.95) AS P95_BYTES_SCANNED,
    SUM(BYTES_SCANNED) AS TOTAL_BYTES_SCANNED,
    SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) AS TOTAL_REMOTE_SPILL_BYTES,
    AVG(PARTITION_SCAN_RATIO) AS AVG_PARTITION_SCAN_RATIO,
    AVG(PERCENTAGE_SCANNED_FROM_CACHE) AS AVG_CACHE_PERCENT,
    MAX_BY(QUERY_TEXT,START_TIME) AS EXAMPLE_QUERY
FROM OPS.V_QUERY_PERFORMANCE_7D
WHERE QUERY_PARAMETERIZED_HASH IS NOT NULL
GROUP BY 1,2;

CREATE OR REPLACE VIEW OPS.V_WAREHOUSE_QUEUE_PRESSURE AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('hour',START_TIME) AS HOUR,
    COUNT(*) AS QUERY_COUNT,
    AVG(QUEUED_OVERLOAD_TIME)/1000 AS AVG_OVERLOAD_QUEUE_SECONDS,
    MAX(QUEUED_OVERLOAD_TIME)/1000 AS MAX_OVERLOAD_QUEUE_SECONDS,
    AVG(QUEUED_PROVISIONING_TIME)/1000 AS AVG_PROVISIONING_SECONDS,
    APPROX_PERCENTILE(TOTAL_ELAPSED_TIME/1000,0.95) AS P95_ELAPSED_SECONDS,
    SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) AS REMOTE_SPILL_BYTES
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-7,CURRENT_TIMESTAMP())
  AND QUERY_TAG ILIKE 'clinical-data-platform%'
GROUP BY 1,2;

-- -----------------------------------------------------------------------------
-- PRUNING / CLUSTERING / STORAGE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW OPS.V_PARTITION_PRUNING AS
SELECT
    QUERY_ID,
    QUERY_PARAMETERIZED_HASH,
    WAREHOUSE_NAME,
    START_TIME,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    DIV0(PARTITIONS_SCANNED,PARTITIONS_TOTAL) AS PARTITION_SCAN_RATIO,
    BYTES_SCANNED,
    TOTAL_ELAPSED_TIME/1000 AS ELAPSED_SECONDS,
    QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-7,CURRENT_TIMESTAMP())
  AND QUERY_TAG ILIKE 'clinical-data-platform%'
  AND PARTITIONS_TOTAL>0;

CREATE OR REPLACE VIEW OPS.V_TABLE_STORAGE_PROFILE AS
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    ACTIVE_BYTES,
    TIME_TRAVEL_BYTES,
    FAILSAFE_BYTES,
    RETAINED_FOR_CLONE_BYTES,
    TABLE_CREATED,
    TABLE_DROPPED
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG='CLINICAL_ANALYTICS'
ORDER BY ACTIVE_BYTES DESC;

-- High-cardinality and skew checks before changing physical design.
SELECT
    COUNT(*) AS ROWS,
    COUNT(DISTINCT EVENT_DATE) AS EVENT_DATES,
    COUNT(DISTINCT EVENT_TYPE) AS EVENT_TYPES,
    COUNT(DISTINCT CLINICAL_TOOL_KEY) AS TOOLS,
    COUNT(DISTINCT ACCOUNT_KEY) AS ACCOUNTS,
    COUNT(DISTINCT USER_TOKEN) AS USERS,
    COUNT(DISTINCT SESSION_ID) AS SESSIONS,
    COUNT(DISTINCT INTEGRATION_ID) AS INTEGRATIONS
FROM CORE.FCT_PRODUCT_EVENT;

SELECT
    EVENT_TYPE,
    COUNT(*) AS ROWS,
    DIV0(COUNT(*),SUM(COUNT(*)) OVER()) AS ROW_SHARE
FROM CORE.FCT_PRODUCT_EVENT
GROUP BY 1
ORDER BY ROWS DESC;

SELECT SYSTEM$CLUSTERING_INFORMATION(
  'CLINICAL_ANALYTICS.CORE.FCT_PRODUCT_EVENT',
  '(EVENT_DATE, EVENT_TYPE)'
) AS PRODUCT_EVENT_CLUSTERING;

SELECT SYSTEM$CLUSTERING_INFORMATION(
  'CLINICAL_ANALYTICS.CORE.FCT_TOOL_COMPLETION',
  '(EVENT_DATE, CLINICAL_TOOL_KEY)'
) AS TOOL_COMPLETION_CLUSTERING;

-- -----------------------------------------------------------------------------
-- RESULT CACHE / SCAN SHAPE / MODEL GRAIN
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW OPS.V_PRODUCT_EVENT_SCAN_PROFILE AS
SELECT
    START_TIME::DATE AS QUERY_DATE,
    WAREHOUSE_NAME,
    COUNT(*) AS QUERY_COUNT,
    SUM(BYTES_SCANNED) AS TOTAL_BYTES_SCANNED,
    AVG(BYTES_SCANNED) AS AVG_BYTES_SCANNED,
    APPROX_PERCENTILE(BYTES_SCANNED,0.95) AS P95_BYTES_SCANNED,
    AVG(PARTITIONS_SCANNED) AS AVG_PARTITIONS_SCANNED,
    AVG(PARTITIONS_TOTAL) AS AVG_PARTITIONS_TOTAL,
    AVG(PERCENTAGE_SCANNED_FROM_CACHE) AS AVG_CACHE_PERCENT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day',-30,CURRENT_TIMESTAMP())
  AND QUERY_TEXT ILIKE '%CORE.FCT_PRODUCT_EVENT%'
  AND EXECUTION_STATUS='SUCCESS'
GROUP BY 1,2;

-- Semantic view avoids CURRENT_DATE in the view definition so result caching remains useful.
CREATE OR REPLACE VIEW MART.V_TOOL_FUNNEL AS
SELECT
    EVENT_DATE,
    CLINICAL_TOOL_KEY,
    TOOL_ID,
    PRIMARY_SPECIALTY,
    CHANNEL,
    COUNTRY_CODE,
    COUNT_IF(EVENT_TYPE='tool_view') AS VIEWS,
    COUNT_IF(EVENT_TYPE='tool_start') AS STARTS,
    COUNT_IF(EVENT_TYPE='tool_complete') AS COMPLETIONS,
    DIV0(COUNT_IF(EVENT_TYPE='tool_start'),COUNT_IF(EVENT_TYPE='tool_view')) AS START_RATE,
    DIV0(COUNT_IF(EVENT_TYPE='tool_complete'),COUNT_IF(EVENT_TYPE='tool_start')) AS COMPLETION_RATE
FROM CORE.FCT_PRODUCT_EVENT
WHERE CLINICAL_TOOL_KEY IS NOT NULL
GROUP BY 1,2,3,4,5,6;

-- Pruning-friendly range query: do not wrap EVENT_TS in DATE() inside the filter.
SELECT
    EVENT_DATE,
    EVENT_TYPE,
    COUNT(*) AS EVENTS
FROM CORE.FCT_PRODUCT_EVENT
WHERE EVENT_TS >= '2026-09-01 00:00:00 +00:00'::TIMESTAMP_TZ
  AND EVENT_TS <  '2026-09-08 00:00:00 +00:00'::TIMESTAMP_TZ
  AND EVENT_TYPE IN ('tool_view','tool_start','tool_complete')
GROUP BY 1,2
ORDER BY 1,2;

-- -----------------------------------------------------------------------------
-- DYNAMIC TABLE / CONTINUOUS QUERY HEALTH
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW OPS.V_DYNAMIC_TABLE_REFRESH_PERFORMANCE AS
SELECT
    NAME,
    SCHEMA_NAME,
    REFRESH_START_TIME,
    REFRESH_END_TIME,
    DATEDIFF('millisecond',REFRESH_START_TIME,REFRESH_END_TIME) AS REFRESH_DURATION_MS,
    COMPLETION_TARGET,
    DATA_TIMESTAMP,
    DATEDIFF('second',DATA_TIMESTAMP,CURRENT_TIMESTAMP()) AS DATA_AGE_SECONDS,
    REFRESH_ACTION,
    REFRESH_TRIGGER,
    STATE,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
  DATE_RANGE_START=>DATEADD('day',-7,CURRENT_TIMESTAMP()),
  DATE_RANGE_END=>CURRENT_TIMESTAMP()
));

CREATE OR REPLACE VIEW OPS.V_DYNAMIC_TABLE_SLO AS
SELECT
    NAME,
    COUNT(*) AS REFRESHES,
    COUNT_IF(STATE<>'SUCCEEDED') AS FAILED_REFRESHES,
    APPROX_PERCENTILE(REFRESH_DURATION_MS,0.50) AS P50_REFRESH_MS,
    APPROX_PERCENTILE(REFRESH_DURATION_MS,0.95) AS P95_REFRESH_MS,
    MAX(DATA_AGE_SECONDS) AS MAX_DATA_AGE_SECONDS
FROM OPS.V_DYNAMIC_TABLE_REFRESH_PERFORMANCE
GROUP BY 1;

-- -----------------------------------------------------------------------------
-- WAREHOUSE COST / RIGHT-SIZING
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW OPS.V_WAREHOUSE_METERING_DAILY AS
SELECT
    START_TIME::DATE AS USAGE_DATE,
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS CREDITS_USED,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day',-30,CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME IN ('INGEST_WH','TRANSFORM_WH','BI_WH')
GROUP BY 1,2
ORDER BY 1 DESC,2;

CREATE OR REPLACE VIEW OPS.V_WAREHOUSE_LOAD AS
SELECT
    START_TIME,
    END_TIME,
    WAREHOUSE_NAME,
    AVG_RUNNING,
    AVG_QUEUED_LOAD,
    AVG_QUEUED_PROVISIONING,
    AVG_BLOCKED
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
WHERE START_TIME >= DATEADD('day',-7,CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME IN ('INGEST_WH','TRANSFORM_WH','BI_WH');

-- -----------------------------------------------------------------------------
-- SEARCH OPTIMIZATION / QUERY ACCELERATION CANDIDATE REVIEW
-- -----------------------------------------------------------------------------
-- Review cardinality and access shape before enabling these services; they add maintenance cost.
SELECT
  COUNT(*) ROWS,
  COUNT(DISTINCT TOOL_ID) TOOL_IDS,
  COUNT(DISTINCT SESSION_ID) SESSION_IDS,
  COUNT(DISTINCT SEARCH_QUERY_TOKEN) QUERY_TOKENS
FROM CORE.FCT_PRODUCT_EVENT;

-- Query Acceleration Service usage/eligibility should be validated using account usage views
-- available in the target Snowflake edition before enabling it on a warehouse.

-- -----------------------------------------------------------------------------
-- CONTROLLED OPTIMIZATION STATEMENTS
-- Run only after the diagnostics above show repeatable benefit.
-- -----------------------------------------------------------------------------
ALTER TABLE CORE.FCT_PRODUCT_EVENT CLUSTER BY (EVENT_DATE, EVENT_TYPE);
ALTER TABLE CORE.FCT_TOOL_COMPLETION CLUSTER BY (EVENT_DATE, CLINICAL_TOOL_KEY);
ALTER TABLE CORE.FCT_SESSION CLUSTER BY (SESSION_DATE, CHANNEL);

-- Exact point lookups on large tables may benefit from Search Optimization Service.
-- ALTER TABLE CORE.DIM_CLINICAL_TOOL ADD SEARCH OPTIMIZATION ON EQUALITY(TOOL_ID, TOOL_SLUG);
-- ALTER TABLE CORE.FCT_PRODUCT_EVENT ADD SEARCH OPTIMIZATION ON EQUALITY(EVENT_ID, SESSION_ID);

-- Example warehouse policy: small baseline with bounded multi-cluster elasticity for BI bursts.
-- ALTER WAREHOUSE BI_WH SET WAREHOUSE_SIZE='SMALL' MIN_CLUSTER_COUNT=1 MAX_CLUSTER_COUNT=3 SCALING_POLICY='ECONOMY' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

-- Performance acceptance gate example: compare candidate query shapes against a stable baseline.
CREATE OR REPLACE VIEW OPS.V_PERFORMANCE_REGRESSION_CANDIDATES AS
SELECT
    QUERY_PARAMETERIZED_HASH,
    WAREHOUSE_NAME,
    EXECUTIONS,
    P95_SECONDS,
    P95_BYTES_SCANNED,
    AVG_PARTITION_SCAN_RATIO,
    TOTAL_REMOTE_SPILL_BYTES,
    CASE
      WHEN P95_SECONDS >= 10 OR TOTAL_REMOTE_SPILL_BYTES > 0 OR AVG_PARTITION_SCAN_RATIO > 0.80 THEN 'REVIEW'
      WHEN P95_SECONDS >= 5 OR AVG_PARTITION_SCAN_RATIO > 0.50 THEN 'WATCH'
      ELSE 'HEALTHY'
    END AS OPTIMIZATION_STATUS
FROM OPS.V_EXPENSIVE_QUERY_SHAPES;
