USE DATABASE CLINICAL_ANALYTICS;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS JSON_EVENTS
  TYPE=JSON
  STRIP_OUTER_ARRAY=FALSE
  ALLOW_DUPLICATE=FALSE
  IGNORE_UTF8_ERRORS=FALSE;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FILES
  TYPE=PARQUET
  USE_LOGICAL_TYPE=TRUE;

CREATE FILE FORMAT IF NOT EXISTS CSV_EXPORTS
  TYPE=CSV
  FIELD_DELIMITER=','
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  SKIP_HEADER=1
  NULL_IF=('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL=TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH=TRUE;

-- Storage integrations are created separately because cloud IAM configuration is environment-specific.
-- The stage paths below are project-owned examples and should be parameterized by deployment tooling.
CREATE STAGE IF NOT EXISTS PRODUCT_EVENTS_STAGE
  URL='s3://clinical-data-prod-raw/product_api/product_event/'
  FILE_FORMAT=JSON_EVENTS
  DIRECTORY=(ENABLE=TRUE)
  COMMENT='Immutable product event landing prefix';

CREATE STAGE IF NOT EXISTS CLINICAL_TOOL_STAGE
  URL='s3://clinical-data-prod-raw/clinical_content_service/clinical_tool/'
  FILE_FORMAT=JSON_EVENTS
  DIRECTORY=(ENABLE=TRUE)
  COMMENT='Clinical tool metadata snapshots';

CREATE STAGE IF NOT EXISTS CONTENT_STAGE
  URL='s3://clinical-data-prod-raw/clinical_content_service/content/'
  FILE_FORMAT=JSON_EVENTS
  DIRECTORY=(ENABLE=TRUE)
  COMMENT='Content catalog snapshots';

CREATE STAGE IF NOT EXISTS CURATED_EXPORT_STAGE
  URL='s3://clinical-data-prod-curated/'
  FILE_FORMAT=PARQUET_FILES
  DIRECTORY=(ENABLE=TRUE)
  COMMENT='Approved curated data-product exports';

CREATE OR REPLACE VIEW GOVERNANCE.V_STAGE_DIRECTORY AS
SELECT 'PRODUCT_EVENTS_STAGE' AS STAGE_NAME, RELATIVE_PATH, SIZE, LAST_MODIFIED, MD5
FROM DIRECTORY(@PRODUCT_EVENTS_STAGE)
UNION ALL
SELECT 'CLINICAL_TOOL_STAGE', RELATIVE_PATH, SIZE, LAST_MODIFIED, MD5
FROM DIRECTORY(@CLINICAL_TOOL_STAGE)
UNION ALL
SELECT 'CONTENT_STAGE', RELATIVE_PATH, SIZE, LAST_MODIFIED, MD5
FROM DIRECTORY(@CONTENT_STAGE);
