-- Clinical decision-support analytical warehouse
-- This file is intentionally self-contained so a clean Snowflake account can review the
-- complete object model: schemas, raw landing, canonical entities, facts, audit controls,
-- streams, tasks, merge procedures, and operational views.

CREATE DATABASE IF NOT EXISTS CLINICAL_ANALYTICS;
USE DATABASE CLINICAL_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW COMMENT='Immutable source-preserving landing tables';
CREATE SCHEMA IF NOT EXISTS STAGING COMMENT='Typed and normalized transformation inputs';
CREATE SCHEMA IF NOT EXISTS CORE COMMENT='Conformed dimensions and canonical facts';
CREATE SCHEMA IF NOT EXISTS MART COMMENT='Business-facing analytical data products';
CREATE SCHEMA IF NOT EXISTS OPS COMMENT='Pipeline control, reconciliation and observability';
CREATE SCHEMA IF NOT EXISTS GOVERNANCE COMMENT='Ownership, classification and lineage metadata';

CREATE OR REPLACE FILE FORMAT RAW.JSON_EVENTS
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE
  ENABLE_OCTAL = FALSE
  ALLOW_DUPLICATE = FALSE
  IGNORE_UTF8_ERRORS = FALSE
  COMMENT = 'Canonical newline JSON event format';

CREATE OR REPLACE FILE FORMAT RAW.CSV_BATCH
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE TABLE IF NOT EXISTS OPS.PIPELINE_RUN (
    RUN_ID STRING NOT NULL,
    PIPELINE_NAME STRING NOT NULL,
    SCHEDULED_FOR TIMESTAMP_TZ,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    STATUS STRING NOT NULL,
    SOURCE_WATERMARK_LOW TIMESTAMP_TZ,
    SOURCE_WATERMARK_HIGH TIMESTAMP_TZ,
    SOURCE_COUNT NUMBER(38,0) DEFAULT 0,
    ACCEPTED_COUNT NUMBER(38,0) DEFAULT 0,
    QUARANTINED_COUNT NUMBER(38,0) DEFAULT 0,
    INSERTED_COUNT NUMBER(38,0) DEFAULT 0,
    UPDATED_COUNT NUMBER(38,0) DEFAULT 0,
    DUPLICATE_COUNT NUMBER(38,0) DEFAULT 0,
    STALE_COUNT NUMBER(38,0) DEFAULT 0,
    UNCHANGED_COUNT NUMBER(38,0) DEFAULT 0,
    PUBLISHED_COUNT NUMBER(38,0) DEFAULT 0,
    ERROR_CLASS STRING,
    ERROR_MESSAGE STRING,
    QUERY_TAG STRING,
    GIT_SHA STRING,
    PRIMARY KEY (RUN_ID)
)
COMMENT='One row per pipeline execution with source-to-target reconciliation counters';

CREATE TABLE IF NOT EXISTS OPS.WATERMARK (
    PIPELINE_NAME STRING NOT NULL,
    SOURCE_NAME STRING NOT NULL,
    WATERMARK_NAME STRING NOT NULL,
    WATERMARK_TS TIMESTAMP_TZ,
    WATERMARK_VALUE STRING,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_RUN_ID STRING,
    PRIMARY KEY (PIPELINE_NAME, SOURCE_NAME, WATERMARK_NAME)
)
COMMENT='Committed extraction progress; updated only after downstream publication succeeds';

CREATE TABLE IF NOT EXISTS OPS.QUARANTINE_EVENT (
    QUARANTINE_ID STRING NOT NULL DEFAULT UUID_STRING(),
    RUN_ID STRING NOT NULL,
    EVENT_ID STRING,
    BUSINESS_KEY STRING,
    SOURCE_SYSTEM STRING,
    EVENT_TYPE STRING,
    ERROR_CODE STRING NOT NULL,
    ERROR_FIELD STRING,
    ERROR_MESSAGE STRING,
    RAW_PAYLOAD VARIANT,
    QUARANTINED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    REPLAY_STATUS STRING DEFAULT 'PENDING',
    REPLAYED_AT TIMESTAMP_TZ,
    PRIMARY KEY (QUARANTINE_ID)
)
CLUSTER BY (DATE_TRUNC('DAY', QUARANTINED_AT), ERROR_CODE);

CREATE TABLE IF NOT EXISTS OPS.RECONCILIATION_RESULT (
    RUN_ID STRING NOT NULL,
    CONTROL_NAME STRING NOT NULL,
    SOURCE_VALUE NUMBER(38,6),
    TARGET_VALUE NUMBER(38,6),
    DIFFERENCE_VALUE NUMBER(38,6),
    TOLERANCE_VALUE NUMBER(38,6) DEFAULT 0,
    STATUS STRING NOT NULL,
    DETAILS VARIANT,
    CHECKED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RUN_ID, CONTROL_NAME)
);

CREATE TABLE IF NOT EXISTS OPS.DATA_QUALITY_RESULT (
    RUN_ID STRING NOT NULL,
    MODEL_NAME STRING NOT NULL,
    TEST_NAME STRING NOT NULL,
    SEVERITY STRING NOT NULL,
    STATUS STRING NOT NULL,
    FAILED_ROWS NUMBER(38,0) DEFAULT 0,
    TOTAL_ROWS NUMBER(38,0) DEFAULT 0,
    FAILURE_RATIO FLOAT DEFAULT 0,
    OBSERVED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DETAILS VARIANT,
    PRIMARY KEY (RUN_ID, MODEL_NAME, TEST_NAME)
);

CREATE TABLE IF NOT EXISTS RAW.PRODUCT_EVENT (
    RAW_ID STRING NOT NULL DEFAULT UUID_STRING(),
    INGEST_RUN_ID STRING NOT NULL,
    SOURCE_SYSTEM STRING NOT NULL,
    SOURCE_OBJECT STRING,
    SOURCE_PARTITION STRING,
    SOURCE_OFFSET STRING,
    SOURCE_FILE STRING,
    EVENT_ID STRING,
    EVENT_TYPE STRING,
    EVENT_TS TIMESTAMP_TZ,
    SOURCE_UPDATED_AT TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SCHEMA_VERSION NUMBER(10,0),
    BUSINESS_KEY STRING,
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_HASH STRING,
    PRIMARY KEY (RAW_ID)
)
CLUSTER BY (DATE_TRUNC('DAY', INGESTED_AT), EVENT_TYPE)
COMMENT='Append-only product and integration event landing table';

CREATE TABLE IF NOT EXISTS RAW.CLINICAL_TOOL_SNAPSHOT (
    INGEST_RUN_ID STRING NOT NULL,
    SOURCE_TOOL_ID STRING NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_HASH STRING NOT NULL,
    PRIMARY KEY (INGEST_RUN_ID, SOURCE_TOOL_ID)
);

CREATE TABLE IF NOT EXISTS RAW.CONTENT_SNAPSHOT (
    INGEST_RUN_ID STRING NOT NULL,
    SOURCE_CONTENT_ID STRING NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_HASH STRING NOT NULL,
    PRIMARY KEY (INGEST_RUN_ID, SOURCE_CONTENT_ID)
);

CREATE TABLE IF NOT EXISTS STAGING.PRODUCT_EVENT (
    EVENT_ID STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_TS TIMESTAMP_TZ NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_SYSTEM STRING NOT NULL,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    BUSINESS_KEY STRING NOT NULL,
    SESSION_ID STRING,
    TOOL_ID STRING,
    CONTENT_ID STRING,
    ACCOUNT_TOKEN STRING,
    USER_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    LANGUAGE_CODE STRING,
    INTEGRATION_ID STRING,
    SEARCH_QUERY_TOKEN STRING,
    COMPLETION_ID STRING,
    CANONICAL_HASH STRING NOT NULL,
    NORMALIZED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
)
CLUSTER BY (DATE_TRUNC('DAY', EVENT_TS), EVENT_TYPE);

CREATE TABLE IF NOT EXISTS CORE.DIM_CLINICAL_TOOL (
    CLINICAL_TOOL_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    TOOL_ID STRING NOT NULL,
    TOOL_SLUG STRING,
    TOOL_NAME STRING NOT NULL,
    PRIMARY_SPECIALTY STRING,
    CONDITION_GROUP STRING,
    EVIDENCE_STATUS STRING,
    PUBLICATION_STATUS STRING,
    FIRST_PUBLISHED_AT TIMESTAMP_TZ,
    LAST_REVIEWED_AT TIMESTAMP_TZ,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    ROW_HASH STRING NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLINICAL_TOOL_KEY)
)
COMMENT='Type-2 history for clinical decision-support tool metadata';

CREATE TABLE IF NOT EXISTS CORE.DIM_CONTENT (
    CONTENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CONTENT_ID STRING NOT NULL,
    CONTENT_TYPE STRING NOT NULL,
    TITLE STRING,
    SPECIALTY STRING,
    CONDITION_GROUP STRING,
    PUBLICATION_STATUS STRING,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    ROW_HASH STRING NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CONTENT_KEY)
);

CREATE TABLE IF NOT EXISTS CORE.DIM_ACCOUNT (
    ACCOUNT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ACCOUNT_TOKEN STRING NOT NULL,
    ACCOUNT_TYPE STRING,
    ORGANIZATION_TOKEN STRING,
    COUNTRY_CODE STRING,
    CREATED_DATE DATE,
    FIRST_SEEN_AT TIMESTAMP_TZ,
    LAST_SEEN_AT TIMESTAMP_TZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ACCOUNT_KEY)
);

CREATE TABLE IF NOT EXISTS CORE.FCT_PRODUCT_EVENT (
    EVENT_ID STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_TS TIMESTAMP_TZ NOT NULL,
    EVENT_DATE DATE NOT NULL,
    BUSINESS_KEY STRING NOT NULL,
    SESSION_ID STRING,
    CLINICAL_TOOL_KEY NUMBER,
    CONTENT_KEY NUMBER,
    ACCOUNT_KEY NUMBER,
    USER_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    LANGUAGE_CODE STRING,
    INTEGRATION_ID STRING,
    SEARCH_QUERY_TOKEN STRING,
    COMPLETION_ID STRING,
    SOURCE_SYSTEM STRING NOT NULL,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    CANONICAL_HASH STRING NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
)
CLUSTER BY (EVENT_DATE, EVENT_TYPE);

CREATE TABLE IF NOT EXISTS CORE.FCT_SESSION (
    SESSION_ID STRING NOT NULL,
    SESSION_DATE DATE NOT NULL,
    ACCOUNT_KEY NUMBER,
    USER_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    ENDED_AT TIMESTAMP_TZ,
    DURATION_SECONDS NUMBER(38,0),
    TOOL_VIEWS NUMBER(38,0) DEFAULT 0,
    TOOL_STARTS NUMBER(38,0) DEFAULT 0,
    TOOL_COMPLETIONS NUMBER(38,0) DEFAULT 0,
    SEARCHES NUMBER(38,0) DEFAULT 0,
    CONTENT_VIEWS NUMBER(38,0) DEFAULT 0,
    FIRST_EVENT_ID STRING,
    LAST_EVENT_ID STRING,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SESSION_ID)
)
CLUSTER BY (SESSION_DATE, CHANNEL);

CREATE TABLE IF NOT EXISTS CORE.FCT_TOOL_COMPLETION (
    COMPLETION_ID STRING NOT NULL,
    EVENT_ID STRING NOT NULL,
    EVENT_TS TIMESTAMP_TZ NOT NULL,
    EVENT_DATE DATE NOT NULL,
    SESSION_ID STRING,
    CLINICAL_TOOL_KEY NUMBER NOT NULL,
    ACCOUNT_KEY NUMBER,
    USER_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    INTEGRATION_ID STRING,
    SOURCE_SYSTEM STRING NOT NULL,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COMPLETION_ID)
)
CLUSTER BY (EVENT_DATE, CLINICAL_TOOL_KEY);

CREATE OR REPLACE VIEW MART.V_PRODUCT_DAILY AS
SELECT
    EVENT_DATE,
    CHANNEL,
    COUNTRY_CODE,
    COUNT_IF(EVENT_TYPE = 'session_start') AS SESSIONS_STARTED,
    COUNT_IF(EVENT_TYPE = 'search') AS SEARCHES,
    COUNT_IF(EVENT_TYPE = 'tool_view') AS TOOL_VIEWS,
    COUNT_IF(EVENT_TYPE = 'tool_start') AS TOOL_STARTS,
    COUNT_IF(EVENT_TYPE = 'tool_complete') AS TOOL_COMPLETIONS,
    COUNT_IF(EVENT_TYPE = 'content_view') AS CONTENT_VIEWS,
    COUNT(DISTINCT USER_TOKEN) AS UNIQUE_USERS,
    COUNT(DISTINCT ACCOUNT_KEY) AS UNIQUE_ACCOUNTS,
    DIV0(COUNT_IF(EVENT_TYPE = 'tool_complete'), COUNT_IF(EVENT_TYPE = 'tool_start')) AS COMPLETION_RATE
FROM CORE.FCT_PRODUCT_EVENT
GROUP BY 1,2,3;

CREATE OR REPLACE VIEW MART.V_TOOL_ENGAGEMENT_DAILY AS
SELECT
    E.EVENT_DATE,
    T.TOOL_ID,
    T.TOOL_NAME,
    T.PRIMARY_SPECIALTY,
    E.CHANNEL,
    COUNT_IF(E.EVENT_TYPE='tool_view') AS VIEWS,
    COUNT_IF(E.EVENT_TYPE='tool_start') AS STARTS,
    COUNT_IF(E.EVENT_TYPE='tool_complete') AS COMPLETIONS,
    COUNT(DISTINCT E.USER_TOKEN) AS UNIQUE_USERS,
    DIV0(COUNT_IF(E.EVENT_TYPE='tool_start'), COUNT_IF(E.EVENT_TYPE='tool_view')) AS START_RATE,
    DIV0(COUNT_IF(E.EVENT_TYPE='tool_complete'), COUNT_IF(E.EVENT_TYPE='tool_start')) AS COMPLETION_RATE
FROM CORE.FCT_PRODUCT_EVENT E
JOIN CORE.DIM_CLINICAL_TOOL T
  ON E.CLINICAL_TOOL_KEY = T.CLINICAL_TOOL_KEY
 AND T.IS_CURRENT = TRUE
GROUP BY 1,2,3,4,5;

CREATE OR REPLACE VIEW MART.V_SPECIALTY_ENGAGEMENT AS
SELECT
    E.EVENT_DATE,
    T.PRIMARY_SPECIALTY,
    COUNT(DISTINCT E.USER_TOKEN) AS UNIQUE_USERS,
    COUNT(DISTINCT E.SESSION_ID) AS SESSIONS,
    COUNT_IF(E.EVENT_TYPE='tool_view') AS TOOL_VIEWS,
    COUNT_IF(E.EVENT_TYPE='tool_complete') AS COMPLETIONS
FROM CORE.FCT_PRODUCT_EVENT E
JOIN CORE.DIM_CLINICAL_TOOL T
  ON E.CLINICAL_TOOL_KEY = T.CLINICAL_TOOL_KEY
 AND T.IS_CURRENT = TRUE
GROUP BY 1,2;

CREATE OR REPLACE VIEW OPS.V_PIPELINE_HEALTH AS
SELECT
    PIPELINE_NAME,
    MAX(STARTED_AT) AS LAST_STARTED_AT,
    MAX(COMPLETED_AT) AS LAST_COMPLETED_AT,
    MAX_BY(STATUS, STARTED_AT) AS LAST_STATUS,
    MAX_BY(SOURCE_COUNT, STARTED_AT) AS LAST_SOURCE_COUNT,
    MAX_BY(QUARANTINED_COUNT, STARTED_AT) AS LAST_QUARANTINED_COUNT,
    MAX_BY(PUBLISHED_COUNT, STARTED_AT) AS LAST_PUBLISHED_COUNT,
    DATEDIFF('minute', MAX(COMPLETED_AT), CURRENT_TIMESTAMP()) AS MINUTES_SINCE_SUCCESS
FROM OPS.PIPELINE_RUN
GROUP BY PIPELINE_NAME;

CREATE OR REPLACE VIEW OPS.V_RECONCILIATION_HEALTH AS
SELECT
    RUN_ID,
    COUNT(*) AS CONTROL_COUNT,
    COUNT_IF(STATUS='PASS') AS PASS_COUNT,
    COUNT_IF(STATUS<>'PASS') AS FAIL_COUNT,
    MAX(ABS(DIFFERENCE_VALUE)) AS MAX_ABS_DIFFERENCE
FROM OPS.RECONCILIATION_RESULT
GROUP BY RUN_ID;

CREATE STREAM IF NOT EXISTS STAGING.PRODUCT_EVENT_STREAM
ON TABLE STAGING.PRODUCT_EVENT
APPEND_ONLY = TRUE
COMMENT='Incremental change feed consumed by warehouse merge task';

CREATE OR REPLACE PROCEDURE OPS.MERGE_PRODUCT_EVENTS()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    inserted_count NUMBER DEFAULT 0;
    updated_count NUMBER DEFAULT 0;
BEGIN
    MERGE INTO CORE.FCT_PRODUCT_EVENT T
    USING (
        SELECT
            S.EVENT_ID,
            S.EVENT_TYPE,
            S.EVENT_TS,
            TO_DATE(S.EVENT_TS) AS EVENT_DATE,
            S.BUSINESS_KEY,
            S.SESSION_ID,
            CT.CLINICAL_TOOL_KEY,
            C.CONTENT_KEY,
            A.ACCOUNT_KEY,
            S.USER_TOKEN,
            S.CHANNEL,
            S.COUNTRY_CODE,
            S.LANGUAGE_CODE,
            S.INTEGRATION_ID,
            S.SEARCH_QUERY_TOKEN,
            S.COMPLETION_ID,
            S.SOURCE_SYSTEM,
            S.SOURCE_VERSION,
            S.SOURCE_UPDATED_AT,
            S.CANONICAL_HASH
        FROM STAGING.PRODUCT_EVENT_STREAM S
        LEFT JOIN CORE.DIM_CLINICAL_TOOL CT
          ON S.TOOL_ID = CT.TOOL_ID AND CT.IS_CURRENT = TRUE
        LEFT JOIN CORE.DIM_CONTENT C
          ON S.CONTENT_ID = C.CONTENT_ID AND C.IS_CURRENT = TRUE
        LEFT JOIN CORE.DIM_ACCOUNT A
          ON S.ACCOUNT_TOKEN = A.ACCOUNT_TOKEN
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY S.EVENT_ID
            ORDER BY S.SOURCE_VERSION DESC, S.SOURCE_UPDATED_AT DESC
        ) = 1
    ) S
    ON T.EVENT_ID = S.EVENT_ID
    WHEN MATCHED AND (
        S.SOURCE_VERSION > T.SOURCE_VERSION OR
        (S.SOURCE_VERSION = T.SOURCE_VERSION AND S.SOURCE_UPDATED_AT > T.SOURCE_UPDATED_AT)
    ) THEN UPDATE SET
        T.EVENT_TYPE = S.EVENT_TYPE,
        T.EVENT_TS = S.EVENT_TS,
        T.EVENT_DATE = S.EVENT_DATE,
        T.BUSINESS_KEY = S.BUSINESS_KEY,
        T.SESSION_ID = S.SESSION_ID,
        T.CLINICAL_TOOL_KEY = S.CLINICAL_TOOL_KEY,
        T.CONTENT_KEY = S.CONTENT_KEY,
        T.ACCOUNT_KEY = S.ACCOUNT_KEY,
        T.USER_TOKEN = S.USER_TOKEN,
        T.CHANNEL = S.CHANNEL,
        T.COUNTRY_CODE = S.COUNTRY_CODE,
        T.LANGUAGE_CODE = S.LANGUAGE_CODE,
        T.INTEGRATION_ID = S.INTEGRATION_ID,
        T.SEARCH_QUERY_TOKEN = S.SEARCH_QUERY_TOKEN,
        T.COMPLETION_ID = S.COMPLETION_ID,
        T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
        T.SOURCE_VERSION = S.SOURCE_VERSION,
        T.SOURCE_UPDATED_AT = S.SOURCE_UPDATED_AT,
        T.CANONICAL_HASH = S.CANONICAL_HASH,
        T.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        EVENT_ID, EVENT_TYPE, EVENT_TS, EVENT_DATE, BUSINESS_KEY, SESSION_ID,
        CLINICAL_TOOL_KEY, CONTENT_KEY, ACCOUNT_KEY, USER_TOKEN, CHANNEL,
        COUNTRY_CODE, LANGUAGE_CODE, INTEGRATION_ID, SEARCH_QUERY_TOKEN,
        COMPLETION_ID, SOURCE_SYSTEM, SOURCE_VERSION, SOURCE_UPDATED_AT,
        CANONICAL_HASH, CREATED_AT, UPDATED_AT
    ) VALUES (
        S.EVENT_ID, S.EVENT_TYPE, S.EVENT_TS, S.EVENT_DATE, S.BUSINESS_KEY,
        S.SESSION_ID, S.CLINICAL_TOOL_KEY, S.CONTENT_KEY, S.ACCOUNT_KEY,
        S.USER_TOKEN, S.CHANNEL, S.COUNTRY_CODE, S.LANGUAGE_CODE,
        S.INTEGRATION_ID, S.SEARCH_QUERY_TOKEN, S.COMPLETION_ID,
        S.SOURCE_SYSTEM, S.SOURCE_VERSION, S.SOURCE_UPDATED_AT,
        S.CANONICAL_HASH, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    );

    RETURN OBJECT_CONSTRUCT(
        'status', 'complete',
        'processed_at', CURRENT_TIMESTAMP(),
        'stream_has_data', SYSTEM$STREAM_HAS_DATA('STAGING.PRODUCT_EVENT_STREAM')
    );
END;
$$;

CREATE TASK IF NOT EXISTS OPS.TASK_MERGE_PRODUCT_EVENTS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('STAGING.PRODUCT_EVENT_STREAM')
AS
    CALL OPS.MERGE_PRODUCT_EVENTS();

CREATE OR REPLACE VIEW GOVERNANCE.V_OBJECT_CATALOG AS
SELECT 'CORE.DIM_CLINICAL_TOOL' AS OBJECT_NAME, 'data-platform' AS OWNER_TEAM, 'clinical metadata' AS DOMAIN, 'daily' AS EXPECTED_FRESHNESS
UNION ALL SELECT 'CORE.FCT_PRODUCT_EVENT', 'data-platform', 'product analytics', '15 minutes'
UNION ALL SELECT 'CORE.FCT_SESSION', 'data-platform', 'product analytics', '30 minutes'
UNION ALL SELECT 'MART.V_PRODUCT_DAILY', 'analytics', 'business intelligence', 'hourly'
UNION ALL SELECT 'MART.V_TOOL_ENGAGEMENT_DAILY', 'analytics', 'product analytics', 'hourly';

CREATE OR REPLACE VIEW OPS.V_STORAGE_AND_SCAN_USAGE AS
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    ACTIVE_BYTES,
    TIME_TRAVEL_BYTES,
    FAILSAFE_BYTES
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG = 'CLINICAL_ANALYTICS';

-- Operational enablement remains explicit. Tasks are created suspended by default in many
-- environments; promotion tooling can issue ALTER TASK ... RESUME after validation gates pass.
