-- Clinical Decision Support Data Platform — enterprise Snowflake reference
-- Portfolio/reference implementation informed by publicly described clinical decision-support
-- product patterns. Generated/de-identified data only; no real patient data is included.
--
-- Review order:
--   1. Schemas / control tables
--   2. Immutable RAW landing
--   3. Normalized STAGING contracts
--   4. Conformed CORE dimensions/facts
--   5. MART serving layer
--   6. FEATURES / MLOps offline features
--   7. GOVERNANCE / lineage
--   8. Streams / merge / operational views

CREATE DATABASE IF NOT EXISTS CLINICAL_ANALYTICS;
USE DATABASE CLINICAL_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW COMMENT='Immutable source-preserving landing';
CREATE SCHEMA IF NOT EXISTS STAGING COMMENT='Typed normalized contract-valid records';
CREATE SCHEMA IF NOT EXISTS CORE COMMENT='Conformed dimensions and canonical facts';
CREATE SCHEMA IF NOT EXISTS MART COMMENT='Business-facing analytical products';
CREATE SCHEMA IF NOT EXISTS OPS COMMENT='Pipeline control, quality, reconciliation and SLO state';
CREATE SCHEMA IF NOT EXISTS GOVERNANCE COMMENT='Ownership, classification and lineage metadata';
CREATE SCHEMA IF NOT EXISTS FEATURES COMMENT='Point-in-time-correct offline ML feature products';

CREATE OR REPLACE FILE FORMAT RAW.JSON_EVENTS
  TYPE=JSON STRIP_OUTER_ARRAY=FALSE ENABLE_OCTAL=FALSE ALLOW_DUPLICATE=FALSE
  IGNORE_UTF8_ERRORS=FALSE COMMENT='Canonical newline-delimited JSON event format';

CREATE OR REPLACE FILE FORMAT RAW.CSV_BATCH
  TYPE=CSV FIELD_DELIMITER=',' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1
  NULL_IF=('','NULL','null') EMPTY_FIELD_AS_NULL=TRUE ERROR_ON_COLUMN_COUNT_MISMATCH=TRUE;

-- -----------------------------------------------------------------------------
-- OPS CONTROL PLANE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS OPS.PIPELINE_RUN (
    RUN_ID STRING NOT NULL,
    PIPELINE_NAME STRING NOT NULL,
    SCHEDULED_FOR TIMESTAMP_TZ,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    STATUS STRING NOT NULL,
    SOURCE_WATERMARK_LOW TIMESTAMP_TZ,
    SOURCE_WATERMARK_HIGH TIMESTAMP_TZ,
    SOURCE_COUNT NUMBER(38,0) DEFAULT 0,
    ACCEPTED_COUNT NUMBER(38,0) DEFAULT 0,
    QUARANTINED_COUNT NUMBER(38,0) DEFAULT 0,
    INSERTED_COUNT NUMBER(38,0) DEFAULT 0,
    UPDATED_COUNT NUMBER(38,0) DEFAULT 0,
    DUPLICATE_COUNT NUMBER(38,0) DEFAULT 0,
    STALE_COUNT NUMBER(38,0) DEFAULT 0,
    UNCHANGED_COUNT NUMBER(38,0) DEFAULT 0,
    PUBLISHED_COUNT NUMBER(38,0) DEFAULT 0,
    ERROR_CLASS STRING,
    ERROR_MESSAGE STRING,
    QUERY_TAG STRING,
    GIT_SHA STRING,
    PRIMARY KEY (RUN_ID)
) COMMENT='One row per pipeline execution with terminal-outcome accounting';

CREATE TABLE IF NOT EXISTS OPS.WATERMARK (
    PIPELINE_NAME STRING NOT NULL,
    SOURCE_NAME STRING NOT NULL,
    WATERMARK_NAME STRING NOT NULL,
    WATERMARK_TS TIMESTAMP_TZ,
    WATERMARK_VALUE STRING,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_RUN_ID STRING,
    PRIMARY KEY (PIPELINE_NAME,SOURCE_NAME,WATERMARK_NAME)
) COMMENT='Committed extraction progress; advances only after downstream gates pass';

CREATE TABLE IF NOT EXISTS OPS.QUARANTINE_EVENT (
    QUARANTINE_ID STRING NOT NULL DEFAULT UUID_STRING(),
    RUN_ID STRING NOT NULL,
    EVENT_ID STRING,
    BUSINESS_KEY STRING,
    SOURCE_SYSTEM STRING,
    EVENT_TYPE STRING,
    ERROR_CODE STRING NOT NULL,
    ERROR_FIELD STRING,
    ERROR_MESSAGE STRING,
    RAW_PAYLOAD VARIANT,
    QUARANTINED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    REPLAY_STATUS STRING DEFAULT 'PENDING',
    REPLAYED_AT TIMESTAMP_TZ,
    PRIMARY KEY (QUARANTINE_ID)
) CLUSTER BY (DATE_TRUNC('DAY',QUARANTINED_AT),ERROR_CODE);

CREATE TABLE IF NOT EXISTS OPS.RECONCILIATION_RESULT (
    RUN_ID STRING NOT NULL,
    CONTROL_NAME STRING NOT NULL,
    SOURCE_VALUE NUMBER(38,6),
    TARGET_VALUE NUMBER(38,6),
    DIFFERENCE_VALUE NUMBER(38,6),
    TOLERANCE_VALUE NUMBER(38,6) DEFAULT 0,
    STATUS STRING NOT NULL,
    DETAILS VARIANT,
    CHECKED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RUN_ID,CONTROL_NAME)
);

CREATE TABLE IF NOT EXISTS OPS.DATA_QUALITY_RESULT (
    RUN_ID STRING NOT NULL,
    MODEL_NAME STRING NOT NULL,
    TEST_NAME STRING NOT NULL,
    SEVERITY STRING NOT NULL,
    STATUS STRING NOT NULL,
    FAILED_ROWS NUMBER(38,0) DEFAULT 0,
    TOTAL_ROWS NUMBER(38,0) DEFAULT 0,
    FAILURE_RATIO FLOAT DEFAULT 0,
    OBSERVED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DETAILS VARIANT,
    PRIMARY KEY (RUN_ID,MODEL_NAME,TEST_NAME)
);

CREATE TABLE IF NOT EXISTS OPS.MODEL_DEPLOYMENT (
    MODEL_NAME STRING NOT NULL,
    MODEL_VERSION STRING NOT NULL,
    STAGE STRING NOT NULL,
    ALGORITHM STRING,
    FEATURE_SCHEMA_HASH STRING,
    DATASET_SNAPSHOT_ID STRING,
    GIT_SHA STRING,
    ARTIFACT_URI STRING,
    DEPLOYED_AT TIMESTAMP_TZ,
    RETIRED_AT TIMESTAMP_TZ,
    METRICS VARIANT,
    APPROVALS VARIANT,
    PRIMARY KEY (MODEL_NAME,MODEL_VERSION)
) COMMENT='MLOps model registry mirror for operational reporting';

CREATE TABLE IF NOT EXISTS OPS.MODEL_SERVICE_METRIC (
    MODEL_NAME STRING NOT NULL,
    MODEL_VERSION STRING NOT NULL,
    METRIC_TS TIMESTAMP_TZ NOT NULL,
    REQUEST_COUNT NUMBER(38,0),
    ERROR_COUNT NUMBER(38,0),
    P50_LATENCY_MS FLOAT,
    P95_LATENCY_MS FLOAT,
    FEATURE_DRIFT_SCORE FLOAT,
    LABEL_METRIC_NAME STRING,
    LABEL_METRIC_VALUE FLOAT,
    DETAILS VARIANT
) CLUSTER BY (DATE_TRUNC('DAY',METRIC_TS),MODEL_NAME);

-- -----------------------------------------------------------------------------
-- RAW — APPEND-ONLY SOURCE PRESERVATION
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS RAW.PRODUCT_EVENT (
    RAW_ID STRING NOT NULL DEFAULT UUID_STRING(),
    INGEST_RUN_ID STRING NOT NULL,
    SOURCE_SYSTEM STRING NOT NULL,
    SOURCE_OBJECT STRING,
    SOURCE_PARTITION STRING,
    SOURCE_OFFSET STRING,
    SOURCE_FILE STRING,
    EVENT_ID STRING,
    EVENT_TYPE STRING,
    EVENT_TS TIMESTAMP_TZ,
    SOURCE_UPDATED_AT TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SCHEMA_VERSION NUMBER(10,0),
    BUSINESS_KEY STRING,
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_HASH STRING,
    TRACE_ID STRING,
    PRIMARY KEY (RAW_ID)
) CLUSTER BY (DATE_TRUNC('DAY',INGESTED_AT),EVENT_TYPE)
  COMMENT='Append-only cross-channel product, search, CME and EHR workflow telemetry';

CREATE TABLE IF NOT EXISTS RAW.CLINICAL_TOOL_SNAPSHOT (
    INGEST_RUN_ID STRING NOT NULL,
    SOURCE_TOOL_ID STRING NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_HASH STRING NOT NULL,
    PRIMARY KEY (INGEST_RUN_ID,SOURCE_TOOL_ID)
) COMMENT='Versioned clinical decision-support tool metadata snapshots';

CREATE TABLE IF NOT EXISTS RAW.CONTENT_SNAPSHOT (
    INGEST_RUN_ID STRING NOT NULL,
    SOURCE_CONTENT_ID STRING NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_HASH STRING NOT NULL,
    PRIMARY KEY (INGEST_RUN_ID,SOURCE_CONTENT_ID)
) COMMENT='Guideline, editorial, educational and CME content snapshots';

CREATE TABLE IF NOT EXISTS RAW.QUALITY_RATING_SNAPSHOT (
    INGEST_RUN_ID STRING NOT NULL,
    RATING_ID STRING NOT NULL,
    TOOL_ID STRING NOT NULL,
    RATING_VERSION STRING NOT NULL,
    OVERALL_SCORE NUMBER(5,2) NOT NULL,
    SCIENTIFIC_SOUNDNESS_SCORE NUMBER(5,2) NOT NULL,
    IMPORTANCE_SCORE NUMBER(5,2) NOT NULL,
    USABILITY_FEASIBILITY_SCORE NUMBER(5,2) NOT NULL,
    FAIRNESS_EQUITY_STATUS STRING,
    DEVELOPMENT_STUDY_COUNT NUMBER(38,0),
    EXTERNAL_VALIDATION_COUNT NUMBER(38,0),
    GUIDELINE_ALIGNMENT_STATUS STRING,
    SOCIETY_GUIDANCE_REFS ARRAY,
    EVIDENCE_REFS ARRAY,
    POPULATION_NOTES STRING,
    LIMITATIONS ARRAY,
    EFFECTIVE_AT TIMESTAMP_TZ NOT NULL,
    RETIRED_AT TIMESTAMP_TZ,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PAYLOAD_HASH STRING NOT NULL,
    PRIMARY KEY (INGEST_RUN_ID,RATING_ID)
) COMMENT='Reference quality-rating metadata; not an internal/proprietary schema';

-- -----------------------------------------------------------------------------
-- STAGING — NORMALIZED CONTRACT SURFACES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS STAGING.PRODUCT_EVENT (
    EVENT_ID STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_TS TIMESTAMP_TZ NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_SYSTEM STRING NOT NULL,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    BUSINESS_KEY STRING NOT NULL,
    SESSION_ID STRING,
    TOOL_ID STRING,
    CONTENT_ID STRING,
    QUALITY_RATING_ID STRING,
    ACCOUNT_TOKEN STRING,
    USER_TOKEN STRING,
    ORGANIZATION_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    LANGUAGE_CODE STRING,
    INTEGRATION_ID STRING,
    SEARCH_QUERY_TOKEN STRING,
    SEARCH_RESULT_RANK NUMBER(38,0),
    COMPLETION_ID STRING,
    RESULT_BAND STRING,
    INPUT_COUNT NUMBER(38,0),
    AUTOFILL_FIELD_COUNT NUMBER(38,0),
    AUTOFILL_CONFIRMED_COUNT NUMBER(38,0),
    CONFIDENCE_BAND STRING,
    RECOMMENDATION_MODEL STRING,
    RECOMMENDATION_POSITION NUMBER(38,0),
    CME_CREDIT_HOURS FLOAT,
    EXPERIMENT_ASSIGNMENTS VARIANT,
    CANONICAL_HASH STRING NOT NULL,
    NORMALIZED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
) CLUSTER BY (DATE_TRUNC('DAY',EVENT_TS),EVENT_TYPE);

-- -----------------------------------------------------------------------------
-- CORE — CONFORMED ENTITIES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CORE.DIM_CLINICAL_TOOL (
    CLINICAL_TOOL_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    TOOL_ID STRING NOT NULL,
    TOOL_SLUG STRING NOT NULL,
    TOOL_NAME STRING NOT NULL,
    TOOL_TYPE STRING,
    SUMMARY STRING,
    PRIMARY_SPECIALTY STRING,
    SPECIALTIES ARRAY,
    CONDITION_GROUP STRING,
    USE_CASES ARRAY,
    INPUT_DEFINITIONS VARIANT,
    OUTPUT_DEFINITIONS VARIANT,
    RESULT_BANDS VARIANT,
    EVIDENCE_STATUS STRING,
    DEVELOPMENT_CITATION STRING,
    VALIDATION_CITATIONS ARRAY,
    GUIDELINE_REFS ARRAY,
    CREATOR_NAMES ARRAY,
    CONTENT_CONTRIBUTORS ARRAY,
    QUALITY_RATING_ID STRING,
    PUBLICATION_STATUS STRING,
    FIRST_PUBLISHED_AT TIMESTAMP_TZ,
    LAST_REVIEWED_AT TIMESTAMP_TZ,
    REVIEW_DUE_AT TIMESTAMP_TZ,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    ROW_HASH STRING NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLINICAL_TOOL_KEY)
) COMMENT='Type-2 clinical tool catalog with evidence and publication metadata';

CREATE TABLE IF NOT EXISTS CORE.DIM_CONTENT (
    CONTENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CONTENT_ID STRING NOT NULL,
    CONTENT_TYPE STRING NOT NULL,
    TITLE STRING NOT NULL,
    SUMMARY STRING,
    SPECIALTY STRING,
    CONDITION_GROUP STRING,
    SOCIETY_NAME STRING,
    GUIDELINE_TITLE STRING,
    GUIDELINE_PUBLICATION_DATE DATE,
    CME_ELIGIBLE BOOLEAN,
    CME_CREDIT_HOURS FLOAT,
    RELATED_TOOL_IDS ARRAY,
    PUBLICATION_STATUS STRING,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    ROW_HASH STRING NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CONTENT_KEY)
);

CREATE TABLE IF NOT EXISTS CORE.DIM_ACCOUNT (
    ACCOUNT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ACCOUNT_TOKEN STRING NOT NULL,
    ACCOUNT_TYPE STRING,
    ORGANIZATION_TOKEN STRING,
    SPECIALTY_TOKEN STRING,
    COUNTRY_CODE STRING,
    CREATED_DATE DATE,
    FIRST_SEEN_AT TIMESTAMP_TZ,
    LAST_SEEN_AT TIMESTAMP_TZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ACCOUNT_KEY)
);

CREATE TABLE IF NOT EXISTS CORE.FCT_PRODUCT_EVENT (
    EVENT_ID STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_TS TIMESTAMP_TZ NOT NULL,
    EVENT_DATE DATE NOT NULL,
    BUSINESS_KEY STRING NOT NULL,
    SESSION_ID STRING,
    TOOL_ID STRING,
    CLINICAL_TOOL_KEY NUMBER,
    PRIMARY_SPECIALTY STRING,
    CONDITION_GROUP STRING,
    TOOL_TYPE STRING,
    CONTENT_ID STRING,
    CONTENT_KEY NUMBER,
    QUALITY_RATING_ID STRING,
    ACCOUNT_TOKEN STRING,
    ACCOUNT_KEY NUMBER,
    USER_TOKEN STRING,
    ORGANIZATION_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    LANGUAGE_CODE STRING,
    INTEGRATION_ID STRING,
    SEARCH_QUERY_TOKEN STRING,
    SEARCH_RESULT_RANK NUMBER(38,0),
    COMPLETION_ID STRING,
    RESULT_BAND STRING,
    INPUT_COUNT NUMBER(38,0),
    AUTOFILL_FIELD_COUNT NUMBER(38,0),
    AUTOFILL_CONFIRMED_COUNT NUMBER(38,0),
    CONFIDENCE_BAND STRING,
    RECOMMENDATION_MODEL STRING,
    RECOMMENDATION_POSITION NUMBER(38,0),
    CME_CREDIT_HOURS FLOAT,
    EXPERIMENT_ASSIGNMENTS VARIANT,
    SOURCE_SYSTEM STRING NOT NULL,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    CANONICAL_HASH STRING NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
) CLUSTER BY (EVENT_DATE,EVENT_TYPE);

CREATE TABLE IF NOT EXISTS CORE.FCT_SESSION (
    SESSION_ID STRING NOT NULL,
    SESSION_DATE DATE NOT NULL,
    ACCOUNT_KEY NUMBER,
    USER_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    ENDED_AT TIMESTAMP_TZ,
    DURATION_SECONDS NUMBER(38,0),
    TOOL_VIEWS NUMBER(38,0) DEFAULT 0,
    TOOL_STARTS NUMBER(38,0) DEFAULT 0,
    TOOL_COMPLETIONS NUMBER(38,0) DEFAULT 0,
    SEARCHES NUMBER(38,0) DEFAULT 0,
    CONTENT_VIEWS NUMBER(38,0) DEFAULT 0,
    FIRST_EVENT_ID STRING,
    LAST_EVENT_ID STRING,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SESSION_ID)
) CLUSTER BY (SESSION_DATE,CHANNEL);

CREATE TABLE IF NOT EXISTS CORE.FCT_TOOL_COMPLETION (
    COMPLETION_ID STRING NOT NULL,
    EVENT_ID STRING NOT NULL,
    EVENT_TS TIMESTAMP_TZ NOT NULL,
    EVENT_DATE DATE NOT NULL,
    SESSION_ID STRING,
    CLINICAL_TOOL_KEY NUMBER NOT NULL,
    ACCOUNT_KEY NUMBER,
    USER_TOKEN STRING,
    CHANNEL STRING,
    COUNTRY_CODE STRING,
    INTEGRATION_ID STRING,
    RESULT_BAND STRING,
    INPUT_COUNT NUMBER(38,0),
    AUTOFILL_FIELD_COUNT NUMBER(38,0),
    AUTOFILL_CONFIRMED_COUNT NUMBER(38,0),
    SOURCE_SYSTEM STRING NOT NULL,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COMPLETION_ID)
) CLUSTER BY (EVENT_DATE,CLINICAL_TOOL_KEY);

CREATE TABLE IF NOT EXISTS CORE.FCT_QUALITY_RATING (
    RATING_KEY NUMBER NOT NULL,
    RATING_ID STRING NOT NULL,
    TOOL_ID STRING NOT NULL,
    CLINICAL_TOOL_KEY NUMBER,
    RATING_VERSION STRING NOT NULL,
    OVERALL_SCORE NUMBER(5,2) NOT NULL,
    SCIENTIFIC_SOUNDNESS_SCORE NUMBER(5,2) NOT NULL,
    IMPORTANCE_SCORE NUMBER(5,2) NOT NULL,
    USABILITY_FEASIBILITY_SCORE NUMBER(5,2) NOT NULL,
    FAIRNESS_EQUITY_STATUS STRING,
    DEVELOPMENT_STUDY_COUNT NUMBER(38,0),
    EXTERNAL_VALIDATION_COUNT NUMBER(38,0),
    GUIDELINE_ALIGNMENT_STATUS STRING,
    SOCIETY_GUIDANCE_REFS ARRAY,
    EVIDENCE_REFS ARRAY,
    POPULATION_NOTES STRING,
    LIMITATIONS ARRAY,
    EFFECTIVE_AT TIMESTAMP_TZ NOT NULL,
    RETIRED_AT TIMESTAMP_TZ,
    SOURCE_VERSION NUMBER(38,0) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    CANONICAL_HASH STRING NOT NULL,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RATING_KEY)
) COMMENT='Reference quality-rating fact with component-score provenance';

-- -----------------------------------------------------------------------------
-- MART — GOVERNED SERVING MODELS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW MART.V_PRODUCT_DAILY AS
SELECT
    EVENT_DATE,CHANNEL,COUNTRY_CODE,
    COUNT_IF(EVENT_TYPE='session_start') SESSIONS_STARTED,
    COUNT_IF(EVENT_TYPE='search') SEARCHES,
    COUNT_IF(EVENT_TYPE='search_result_click') SEARCH_RESULT_CLICKS,
    COUNT_IF(EVENT_TYPE='tool_view') TOOL_VIEWS,
    COUNT_IF(EVENT_TYPE='tool_start') TOOL_STARTS,
    COUNT_IF(EVENT_TYPE='tool_complete') TOOL_COMPLETIONS,
    COUNT_IF(EVENT_TYPE IN ('content_view','guideline_view','cme_content_view')) CONTENT_VIEWS,
    COUNT_IF(EVENT_TYPE='cme_credit_earned') CME_CREDIT_EVENTS,
    SUM(IFF(EVENT_TYPE='cme_credit_earned',COALESCE(CME_CREDIT_HOURS,0),0)) CME_CREDIT_HOURS,
    COUNT(DISTINCT USER_TOKEN) UNIQUE_USERS,
    COUNT(DISTINCT ACCOUNT_KEY) UNIQUE_ACCOUNTS,
    DIV0(COUNT_IF(EVENT_TYPE='tool_complete'),COUNT_IF(EVENT_TYPE='tool_start')) COMPLETION_RATE
FROM CORE.FCT_PRODUCT_EVENT
GROUP BY 1,2,3;

CREATE OR REPLACE VIEW MART.V_TOOL_ENGAGEMENT_DAILY AS
SELECT
    E.EVENT_DATE,E.TOOL_ID,T.TOOL_NAME,T.PRIMARY_SPECIALTY,E.CHANNEL,E.COUNTRY_CODE,
    COUNT_IF(E.EVENT_TYPE='tool_view') VIEWS,
    COUNT_IF(E.EVENT_TYPE='tool_start') STARTS,
    COUNT_IF(E.EVENT_TYPE='tool_complete') COMPLETIONS,
    COUNT_IF(E.EVENT_TYPE='favorite_add') FAVORITE_ADDS,
    COUNT(DISTINCT E.USER_TOKEN) UNIQUE_USERS,
    COUNT(DISTINCT E.SESSION_ID) SESSIONS,
    DIV0(COUNT_IF(E.EVENT_TYPE='tool_start'),COUNT_IF(E.EVENT_TYPE='tool_view')) START_RATE,
    DIV0(COUNT_IF(E.EVENT_TYPE='tool_complete'),COUNT_IF(E.EVENT_TYPE='tool_start')) COMPLETION_RATE
FROM CORE.FCT_PRODUCT_EVENT E
LEFT JOIN CORE.DIM_CLINICAL_TOOL T ON E.CLINICAL_TOOL_KEY=T.CLINICAL_TOOL_KEY
GROUP BY 1,2,3,4,5,6;

CREATE OR REPLACE VIEW MART.V_EHR_INTEGRATION_DAILY AS
SELECT
    EVENT_DATE,COALESCE(INTEGRATION_ID,'unknown') INTEGRATION_ID,
    COUNT_IF(EVENT_TYPE='integration_launch') LAUNCHES,
    COUNT_IF(EVENT_TYPE='ehr_context_open') CONTEXT_OPENS,
    COUNT_IF(EVENT_TYPE='ehr_autofill') AUTOFILL_EVENTS,
    COUNT_IF(EVENT_TYPE='ehr_result_writeback') WRITEBACKS,
    SUM(COALESCE(AUTOFILL_FIELD_COUNT,0)) AUTOFILL_FIELDS,
    SUM(COALESCE(AUTOFILL_CONFIRMED_COUNT,0)) CONFIRMED_FIELDS,
    DIV0(SUM(COALESCE(AUTOFILL_CONFIRMED_COUNT,0)),SUM(COALESCE(AUTOFILL_FIELD_COUNT,0))) CONFIRMATION_RATE,
    COUNT(DISTINCT TOOL_ID) UNIQUE_TOOLS,
    COUNT(DISTINCT ACCOUNT_KEY) UNIQUE_ACCOUNTS
FROM CORE.FCT_PRODUCT_EVENT
WHERE INTEGRATION_ID IS NOT NULL OR EVENT_TYPE LIKE 'ehr_%' OR EVENT_TYPE='integration_launch'
GROUP BY 1,2;

CREATE OR REPLACE VIEW MART.V_QUALITY_TRUST AS
SELECT
    R.TOOL_ID,T.TOOL_NAME,T.PRIMARY_SPECIALTY,R.RATING_VERSION,R.OVERALL_SCORE,
    R.SCIENTIFIC_SOUNDNESS_SCORE,R.IMPORTANCE_SCORE,R.USABILITY_FEASIBILITY_SCORE,
    R.FAIRNESS_EQUITY_STATUS,R.EXTERNAL_VALIDATION_COUNT,R.GUIDELINE_ALIGNMENT_STATUS,
    R.EFFECTIVE_AT,R.RETIRED_AT
FROM CORE.FCT_QUALITY_RATING R
LEFT JOIN CORE.DIM_CLINICAL_TOOL T ON R.CLINICAL_TOOL_KEY=T.CLINICAL_TOOL_KEY;

-- -----------------------------------------------------------------------------
-- FEATURES — OFFLINE FEATURE PRODUCTS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW FEATURES.TOOL_RECOMMENDATION_DAILY AS
SELECT
    EVENT_DATE,USER_TOKEN,TOOL_ID,PRIMARY_SPECIALTY,CHANNEL,
    COUNT_IF(EVENT_TYPE='tool_view') OVER(PARTITION BY USER_TOKEN,TOOL_ID ORDER BY EVENT_DATE ROWS BETWEEN 27 PRECEDING AND CURRENT ROW) USER_TOOL_VIEWS_28D,
    COUNT_IF(EVENT_TYPE='tool_complete') OVER(PARTITION BY USER_TOKEN,TOOL_ID ORDER BY EVENT_DATE ROWS BETWEEN 27 PRECEDING AND CURRENT ROW) USER_TOOL_COMPLETIONS_28D,
    COUNT_IF(EVENT_TYPE='favorite_add') OVER(PARTITION BY USER_TOKEN,TOOL_ID ORDER BY EVENT_DATE ROWS BETWEEN 27 PRECEDING AND CURRENT ROW) USER_TOOL_FAVORITES_28D,
    MAX(EVENT_TS) OVER(PARTITION BY USER_TOKEN,TOOL_ID ORDER BY EVENT_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LAST_USER_TOOL_EVENT_TS
FROM CORE.FCT_PRODUCT_EVENT
WHERE USER_TOKEN IS NOT NULL AND TOOL_ID IS NOT NULL;

CREATE OR REPLACE VIEW FEATURES.EHR_AUTOFILL_FIELD_DAILY AS
SELECT
    EVENT_DATE,INTEGRATION_ID,TOOL_ID,CONFIDENCE_BAND,
    SUM(COALESCE(AUTOFILL_FIELD_COUNT,0)) AUTOFILL_FIELD_COUNT,
    SUM(COALESCE(AUTOFILL_CONFIRMED_COUNT,0)) CONFIRMED_FIELD_COUNT,
    DIV0(SUM(COALESCE(AUTOFILL_CONFIRMED_COUNT,0)),SUM(COALESCE(AUTOFILL_FIELD_COUNT,0))) CONFIRMATION_RATE
FROM CORE.FCT_PRODUCT_EVENT
WHERE EVENT_TYPE='ehr_autofill'
GROUP BY 1,2,3,4;

CREATE OR REPLACE VIEW FEATURES.PIPELINE_RUN_FEATURE AS
SELECT
    RUN_ID,PIPELINE_NAME,STARTED_AT,COMPLETED_AT,SOURCE_COUNT,ACCEPTED_COUNT,QUARANTINED_COUNT,
    DUPLICATE_COUNT,STALE_COUNT,PUBLISHED_COUNT,
    DIV0(QUARANTINED_COUNT,SOURCE_COUNT) QUARANTINE_RATIO,
    DIV0(DUPLICATE_COUNT,SOURCE_COUNT) DUPLICATE_RATIO,
    DIV0(STALE_COUNT,SOURCE_COUNT) STALE_RATIO,
    DATEDIFF('second',STARTED_AT,COMPLETED_AT) DURATION_SECONDS,
    IFF(STATUS='SUCCESS',0,1) FAILURE_LABEL
FROM OPS.PIPELINE_RUN;

-- -----------------------------------------------------------------------------
-- GOVERNANCE / LINEAGE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS GOVERNANCE.DATA_ASSET (
    ASSET_NAME STRING NOT NULL,
    OWNER_TEAM STRING NOT NULL,
    DOMAIN STRING NOT NULL,
    CLASSIFICATION STRING NOT NULL,
    GRAIN STRING,
    PRIMARY_KEY_COLUMNS ARRAY,
    FRESHNESS_SLO_MINUTES NUMBER,
    RETENTION_DAYS NUMBER,
    DESCRIPTION STRING,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ASSET_NAME)
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.LINEAGE_EDGE (
    UPSTREAM_ASSET STRING NOT NULL,
    DOWNSTREAM_ASSET STRING NOT NULL,
    TRANSFORMATION STRING NOT NULL,
    CODE_PATH STRING,
    TRANSFORM_VERSION STRING,
    REGISTERED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (UPSTREAM_ASSET,DOWNSTREAM_ASSET,TRANSFORMATION)
);

MERGE INTO GOVERNANCE.DATA_ASSET T USING (
  SELECT * FROM VALUES
    ('RAW.PRODUCT_EVENT','data-platform','product','pseudonymous','one_row_per_raw_arrival',ARRAY_CONSTRUCT('RAW_ID'),20,90,'Immutable cross-channel event landing'),
    ('CORE.FCT_PRODUCT_EVENT','data-platform','product','pseudonymous','one_row_per_event_id',ARRAY_CONSTRUCT('EVENT_ID'),30,395,'Canonical event fact'),
    ('CORE.DIM_CLINICAL_TOOL','clinical-content','clinical_content','internal','one_row_per_tool_version',ARRAY_CONSTRUCT('CLINICAL_TOOL_KEY'),1440,NULL,'Versioned clinical tool metadata'),
    ('CORE.FCT_QUALITY_RATING','clinical-content','clinical_content','internal','one_row_per_rating_version',ARRAY_CONSTRUCT('RATING_KEY'),1440,NULL,'Reference quality rating history'),
    ('MART.V_EHR_INTEGRATION_DAILY','analytics','integrations','internal','one_row_per_date_integration',ARRAY_CONSTRUCT('EVENT_DATE','INTEGRATION_ID'),60,NULL,'De-identified integration workflow analytics'),
    ('OPS.PIPELINE_RUN','data-platform','platform','internal','one_row_per_run',ARRAY_CONSTRUCT('RUN_ID'),5,395,'Pipeline audit ledger')
) S(ASSET_NAME,OWNER_TEAM,DOMAIN,CLASSIFICATION,GRAIN,PRIMARY_KEY_COLUMNS,FRESHNESS_SLO_MINUTES,RETENTION_DAYS,DESCRIPTION)
ON T.ASSET_NAME=S.ASSET_NAME
WHEN MATCHED THEN UPDATE SET OWNER_TEAM=S.OWNER_TEAM,DOMAIN=S.DOMAIN,CLASSIFICATION=S.CLASSIFICATION,GRAIN=S.GRAIN,
  PRIMARY_KEY_COLUMNS=S.PRIMARY_KEY_COLUMNS,FRESHNESS_SLO_MINUTES=S.FRESHNESS_SLO_MINUTES,RETENTION_DAYS=S.RETENTION_DAYS,
  DESCRIPTION=S.DESCRIPTION,UPDATED_AT=CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT(ASSET_NAME,OWNER_TEAM,DOMAIN,CLASSIFICATION,GRAIN,PRIMARY_KEY_COLUMNS,FRESHNESS_SLO_MINUTES,RETENTION_DAYS,DESCRIPTION)
  VALUES(S.ASSET_NAME,S.OWNER_TEAM,S.DOMAIN,S.CLASSIFICATION,S.GRAIN,S.PRIMARY_KEY_COLUMNS,S.FRESHNESS_SLO_MINUTES,S.RETENTION_DAYS,S.DESCRIPTION);

-- -----------------------------------------------------------------------------
-- STREAMS + CANONICAL MERGE
-- -----------------------------------------------------------------------------
CREATE STREAM IF NOT EXISTS STAGING.PRODUCT_EVENT_STREAM
ON TABLE STAGING.PRODUCT_EVENT APPEND_ONLY=TRUE
COMMENT='Incremental change feed consumed by canonical merge';

CREATE OR REPLACE PROCEDURE OPS.MERGE_PRODUCT_EVENTS()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO CORE.FCT_PRODUCT_EVENT T
    USING (
      SELECT
        S.EVENT_ID,S.EVENT_TYPE,S.EVENT_TS,TO_DATE(S.EVENT_TS) EVENT_DATE,S.BUSINESS_KEY,S.SESSION_ID,
        S.TOOL_ID,CT.CLINICAL_TOOL_KEY,CT.PRIMARY_SPECIALTY,CT.CONDITION_GROUP,CT.TOOL_TYPE,
        S.CONTENT_ID,C.CONTENT_KEY,S.QUALITY_RATING_ID,S.ACCOUNT_TOKEN,A.ACCOUNT_KEY,S.USER_TOKEN,S.ORGANIZATION_TOKEN,
        S.CHANNEL,S.COUNTRY_CODE,S.LANGUAGE_CODE,S.INTEGRATION_ID,S.SEARCH_QUERY_TOKEN,S.SEARCH_RESULT_RANK,
        S.COMPLETION_ID,S.RESULT_BAND,S.INPUT_COUNT,S.AUTOFILL_FIELD_COUNT,S.AUTOFILL_CONFIRMED_COUNT,
        S.CONFIDENCE_BAND,S.RECOMMENDATION_MODEL,S.RECOMMENDATION_POSITION,S.CME_CREDIT_HOURS,S.EXPERIMENT_ASSIGNMENTS,
        S.SOURCE_SYSTEM,S.SOURCE_VERSION,S.SOURCE_UPDATED_AT,S.CANONICAL_HASH
      FROM STAGING.PRODUCT_EVENT_STREAM S
      LEFT JOIN CORE.DIM_CLINICAL_TOOL CT ON S.TOOL_ID=CT.TOOL_ID AND CT.IS_CURRENT
      LEFT JOIN CORE.DIM_CONTENT C ON S.CONTENT_ID=C.CONTENT_ID AND C.IS_CURRENT
      LEFT JOIN CORE.DIM_ACCOUNT A ON S.ACCOUNT_TOKEN=A.ACCOUNT_TOKEN
      QUALIFY ROW_NUMBER() OVER(PARTITION BY S.EVENT_ID ORDER BY S.SOURCE_VERSION DESC,S.SOURCE_UPDATED_AT DESC)=1
    ) S
    ON T.EVENT_ID=S.EVENT_ID
    WHEN MATCHED AND (
      S.SOURCE_VERSION>T.SOURCE_VERSION OR
      (S.SOURCE_VERSION=T.SOURCE_VERSION AND S.SOURCE_UPDATED_AT>T.SOURCE_UPDATED_AT AND S.CANONICAL_HASH<>T.CANONICAL_HASH)
    ) THEN UPDATE SET
      EVENT_TYPE=S.EVENT_TYPE,EVENT_TS=S.EVENT_TS,EVENT_DATE=S.EVENT_DATE,BUSINESS_KEY=S.BUSINESS_KEY,SESSION_ID=S.SESSION_ID,
      TOOL_ID=S.TOOL_ID,CLINICAL_TOOL_KEY=S.CLINICAL_TOOL_KEY,PRIMARY_SPECIALTY=S.PRIMARY_SPECIALTY,CONDITION_GROUP=S.CONDITION_GROUP,
      TOOL_TYPE=S.TOOL_TYPE,CONTENT_ID=S.CONTENT_ID,CONTENT_KEY=S.CONTENT_KEY,QUALITY_RATING_ID=S.QUALITY_RATING_ID,
      ACCOUNT_TOKEN=S.ACCOUNT_TOKEN,ACCOUNT_KEY=S.ACCOUNT_KEY,USER_TOKEN=S.USER_TOKEN,ORGANIZATION_TOKEN=S.ORGANIZATION_TOKEN,
      CHANNEL=S.CHANNEL,COUNTRY_CODE=S.COUNTRY_CODE,LANGUAGE_CODE=S.LANGUAGE_CODE,INTEGRATION_ID=S.INTEGRATION_ID,
      SEARCH_QUERY_TOKEN=S.SEARCH_QUERY_TOKEN,SEARCH_RESULT_RANK=S.SEARCH_RESULT_RANK,COMPLETION_ID=S.COMPLETION_ID,
      RESULT_BAND=S.RESULT_BAND,INPUT_COUNT=S.INPUT_COUNT,AUTOFILL_FIELD_COUNT=S.AUTOFILL_FIELD_COUNT,
      AUTOFILL_CONFIRMED_COUNT=S.AUTOFILL_CONFIRMED_COUNT,CONFIDENCE_BAND=S.CONFIDENCE_BAND,
      RECOMMENDATION_MODEL=S.RECOMMENDATION_MODEL,RECOMMENDATION_POSITION=S.RECOMMENDATION_POSITION,CME_CREDIT_HOURS=S.CME_CREDIT_HOURS,
      EXPERIMENT_ASSIGNMENTS=S.EXPERIMENT_ASSIGNMENTS,SOURCE_SYSTEM=S.SOURCE_SYSTEM,SOURCE_VERSION=S.SOURCE_VERSION,
      SOURCE_UPDATED_AT=S.SOURCE_UPDATED_AT,CANONICAL_HASH=S.CANONICAL_HASH,UPDATED_AT=CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT(
      EVENT_ID,EVENT_TYPE,EVENT_TS,EVENT_DATE,BUSINESS_KEY,SESSION_ID,TOOL_ID,CLINICAL_TOOL_KEY,PRIMARY_SPECIALTY,CONDITION_GROUP,
      TOOL_TYPE,CONTENT_ID,CONTENT_KEY,QUALITY_RATING_ID,ACCOUNT_TOKEN,ACCOUNT_KEY,USER_TOKEN,ORGANIZATION_TOKEN,CHANNEL,
      COUNTRY_CODE,LANGUAGE_CODE,INTEGRATION_ID,SEARCH_QUERY_TOKEN,SEARCH_RESULT_RANK,COMPLETION_ID,RESULT_BAND,INPUT_COUNT,
      AUTOFILL_FIELD_COUNT,AUTOFILL_CONFIRMED_COUNT,CONFIDENCE_BAND,RECOMMENDATION_MODEL,RECOMMENDATION_POSITION,CME_CREDIT_HOURS,
      EXPERIMENT_ASSIGNMENTS,SOURCE_SYSTEM,SOURCE_VERSION,SOURCE_UPDATED_AT,CANONICAL_HASH
    ) VALUES(
      S.EVENT_ID,S.EVENT_TYPE,S.EVENT_TS,S.EVENT_DATE,S.BUSINESS_KEY,S.SESSION_ID,S.TOOL_ID,S.CLINICAL_TOOL_KEY,S.PRIMARY_SPECIALTY,S.CONDITION_GROUP,
      S.TOOL_TYPE,S.CONTENT_ID,S.CONTENT_KEY,S.QUALITY_RATING_ID,S.ACCOUNT_TOKEN,S.ACCOUNT_KEY,S.USER_TOKEN,S.ORGANIZATION_TOKEN,S.CHANNEL,
      S.COUNTRY_CODE,S.LANGUAGE_CODE,S.INTEGRATION_ID,S.SEARCH_QUERY_TOKEN,S.SEARCH_RESULT_RANK,S.COMPLETION_ID,S.RESULT_BAND,S.INPUT_COUNT,
      S.AUTOFILL_FIELD_COUNT,S.AUTOFILL_CONFIRMED_COUNT,S.CONFIDENCE_BAND,S.RECOMMENDATION_MODEL,S.RECOMMENDATION_POSITION,S.CME_CREDIT_HOURS,
      S.EXPERIMENT_ASSIGNMENTS,S.SOURCE_SYSTEM,S.SOURCE_VERSION,S.SOURCE_UPDATED_AT,S.CANONICAL_HASH
    );

    RETURN OBJECT_CONSTRUCT('status','MERGED','rows_affected',SQLROWCOUNT,'merged_at',CURRENT_TIMESTAMP());
END;
$$;

-- -----------------------------------------------------------------------------
-- OPERATIONAL VIEWS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW OPS.V_PIPELINE_HEALTH AS
SELECT
    PIPELINE_NAME,
    MAX_BY(RUN_ID,STARTED_AT) LAST_RUN_ID,
    MAX(STARTED_AT) LAST_STARTED_AT,
    MAX(COMPLETED_AT) LAST_COMPLETED_AT,
    MAX_BY(STATUS,STARTED_AT) LAST_STATUS,
    MAX_BY(SOURCE_COUNT,STARTED_AT) LAST_SOURCE_COUNT,
    MAX_BY(QUARANTINED_COUNT,STARTED_AT) LAST_QUARANTINED_COUNT,
    MAX_BY(PUBLISHED_COUNT,STARTED_AT) LAST_PUBLISHED_COUNT,
    DATEDIFF('minute',MAX(COMPLETED_AT),CURRENT_TIMESTAMP()) MINUTES_SINCE_COMPLETION,
    COUNT_IF(STARTED_AT>=DATEADD('hour',-24,CURRENT_TIMESTAMP()) AND STATUS<>'SUCCESS') FAILURES_24H
FROM OPS.PIPELINE_RUN
GROUP BY PIPELINE_NAME;

CREATE OR REPLACE VIEW OPS.V_RECONCILIATION_HEALTH AS
SELECT
    RUN_ID,
    COUNT(*) CONTROL_COUNT,
    COUNT_IF(STATUS='PASS') PASS_COUNT,
    COUNT_IF(STATUS='WARN') WARN_COUNT,
    COUNT_IF(STATUS='FAIL') FAIL_COUNT,
    MAX(ABS(DIFFERENCE_VALUE)) MAX_ABS_DIFFERENCE,
    MAX(CHECKED_AT) LAST_CHECKED_AT
FROM OPS.RECONCILIATION_RESULT
GROUP BY RUN_ID;

CREATE OR REPLACE VIEW OPS.V_MODEL_HEALTH AS
SELECT
    MODEL_NAME,MODEL_VERSION,
    MAX(METRIC_TS) LAST_METRIC_AT,
    SUM(REQUEST_COUNT) REQUESTS,
    SUM(ERROR_COUNT) ERRORS,
    DIV0(SUM(ERROR_COUNT),SUM(REQUEST_COUNT)) ERROR_RATE,
    MAX_BY(P95_LATENCY_MS,METRIC_TS) LATEST_P95_LATENCY_MS,
    MAX_BY(FEATURE_DRIFT_SCORE,METRIC_TS) LATEST_FEATURE_DRIFT_SCORE,
    MAX_BY(LABEL_METRIC_NAME,METRIC_TS) LATEST_LABEL_METRIC_NAME,
    MAX_BY(LABEL_METRIC_VALUE,METRIC_TS) LATEST_LABEL_METRIC_VALUE
FROM OPS.MODEL_SERVICE_METRIC
WHERE METRIC_TS>=DATEADD('day',-7,CURRENT_TIMESTAMP())
GROUP BY 1,2;

-- Continuous dynamic tables and task graph are defined in:
--   snowflake/streams_tasks/incremental_processing.sql
-- Transactional publication/reconciliation procedures are defined in:
--   snowflake/procedures/merge_and_reconcile.sql
-- Performance diagnostics are defined in:
--   snowflake/performance/query_optimization.sql
